### ISSUE TITLE
Does every user of the app needs to get a access token with upload scope?

### ISSUE THREAD

**Issue by tspvivek** [vimeo/vimeo.php#100]
Hi,
I used this SDK and the app works very well when i login with my developer account, which has access token with upload scope. When i tried login with a user account i am getting the error 'Your access token does not have the "upload" scope'. So is it mandatory for all my app users to get a access token with upload scope.
Thanks

**Comment by Dashron** [comment]
If you wish to upload a video, the access token you are using must have the upload scope.
