### ISSUE TITLE
Uploading over HTTPS

### ISSUE THREAD

**Issue by dulisha** [vimeo/vimeo.php#103]
I manage to make a pull call to Vimeo uploading feature. It's working great on URL's with non https.
Once when HTTPS is active on URL where video file belong, Vimeo reject this.

How i can explore further about this? Vimeo accept my pull request and create the video, but it's never taken from the URL and converted.

**Comment by Dashron** [comment]
Contact vimeo at vimeo.com/help/contact and provide the https video link you are attempting to upload.

We will work on debugging the system!

**Comment by dulisha** [comment]
Thank you Dashron, and for your awesome fast response. I'll do that, and let you know for further assistance.
