### ISSUE TITLE
JSON Filter: passing field array with request params results in improperly-encoded request

### ISSUE THREAD

**Issue by nimmolo** [vimeo/vimeo.php#104]
This may be part of issue #7 .

If i make a request like this:

    $fields_desired = array('name',
                  'link',
                  'description',
                  'pictures',
                  'user',
                  'privacy',
                  'tags',
                  'release_time',
                  );

    $vimeo = new \Vimeo\Vimeo($developer_key, $secret_key, $access_token);

    $videofeed = $vimeo->request('/users/'.$author_id.'/videos',
                                 array('fields' => $fields_desired,
                                          'sort' => 'date',
                                          'filter' => 'embeddable',
                                          'filter_embeddable' => 'true'),
                                 'GET',
                                 true);

The library encodes the JSON like this:
`https://api.vimeo.com/users/468130/videos?fields%5B0%5D=name&fields%5B1%5D=link&fields%5B2%5D=description&fields%5B3%5D=pictures&fields%5B4%5D=user&fields%5B5%5D=privacy&fields%5B6%5D=tags&fields%5B7%5D=release_time&sort=date&filter=embeddable&filter_embeddable=true`

Not good...

Imploding the array doesn't work either.

**Comment by Dashron** [comment]
The parameters array that you pass to the request method must be able to be converted to query string format on any GET request.

Query string format does not support arrays. The Vimeo API will interpret (sometimes) a comma separated list as an array.

This library does not perform any automatic array conversion to a comma separated list. You will need to do that yourself with something like the following

    $fields_desired = implode(',', array('name',
                  'link',
                  'description',
                  'pictures',
                  'user',
                  'privacy',
                  'tags',
                  'release_time',
                  ));

    $vimeo = new \Vimeo\Vimeo($developer_key, $secret_key, $access_token);

    $videofeed = $vimeo->request('/users/'.$author_id.'/videos',
                                 array('fields' => $fields_desired,
                                          'sort' => 'date',
                                          'filter' => 'embeddable',
                                          'filter_embeddable' => 'true'),
                                 'GET',
                                 true);

**Comment by nimmolo** [comment]
Dashron I should have noted I tried what you suggested already and it is incorrectly converted. 

The commas get converted to %2C and the query fails.

I have a hacky workaround that passes the imploded string to the Vimeo->request function, and appends it AFTER the http_build_query, but before it's sent. This required modifying the library's Vimeo.php file like this.

        /**
     * Make an API request to Vimeo.
     *
     * @param string $url A Vimeo API Endpoint. Should not include the host
     * @param array $params An array of parameters to send to the endpoint. If the HTTP method is GET, they will be added to the url, otherwise they will be written to the body
     * @param string $method The HTTP Method of the request
     * @param bool $json_body
     * @return array This array contains three keys, 'status' is the status code, 'body' is an object representation of the json response body, and headers are an associated array of response headers
     */
    public function request($url, $params = array(), $method = 'GET', $json_body = true, $fields_desired = '')
    {
        // add accept header hardcoded to version 3.0
        $headers[] = 'Accept: ' . self::VERSION_STRING;
        $headers[] = 'User-Agent: ' . self::USER_AGENT;

        // add bearer token, or client information
        if (!empty($this->_access_token)) {
            $headers[] = 'Authorization: Bearer ' . $this->_access_token;
        }
        else {
            //  this may be a call to get the tokens, so we add the client info.
            $headers[] = 'Authorization: Basic ' . $this->_authHeader();
        }

        //  Set the methods, determine the URL that we should actually request and prep the body.
        $curl_opts = array();
        switch (strtoupper($method)) {
            case 'GET' :
                if (!empty($params)) {
                    $query_component = '?' . http_build_query($params, '', '&');
                } else {
                    $query_component = '';
                }

                $curl_url = self::ROOT_ENDPOINT . $url . $query_component;
                // NIMMO
                echo $curl_url . '<br />';
                $curl_url = $curl_url . '&fields=' . $fields_desired;
                echo $curl_url;

                break;


This is so hacky though. The JSON filter function seems like it should work out of the box.

**Comment by nimmolo** [comment]
This is somewhat of a separate issue, maybe, but I'd like to point out that nested parameters don't seem to work with GET either.

Adding 

` 'privacy.view' => 'anybody'`

to the params doesn't return filtered results for that parameter.

**Comment by Dashron** [comment]
That's correct. Request bodies are nested JSON, and dot notation is a flat way of describing nested JSON.

Querystrings require the flat description, due to the limitation of the querystring format.

I'll create an issue

**Comment by nimmolo** [comment]
Many thanks. 

Just to clarify the nested/flat issue, i want to restate that the correctly-formed dot notation for filtering by privacy field does *not* work. Passing this param:

`'privacy.view' => 'anybody'`

to Vimeo->request *does* form a correct (flat) query string as 
`METHOD endpoint?privacy.view=anybody`
but the results *are not* filtered as expected.

**Comment by Dashron** [comment]
`METHOD endpoint?privacy.view=anybody` is not a valid request.

`privacy.view` is a field that can be filtered, so you would request:

`endpoint?fields=privacy.view`

So If I request
`endpoint?fields=privacy.view` on a video who's privacy.view is anybody, I will retrieve the following

```
{
    "privacy": {
        "view": "anybody"
    }
}
```

If I want to set the privacy of a video, I would make the following request

`PATCH endpoint`

with the JSON body of 

```
{
    "privacy": {
        "view": "anybody"
    }
}
```

**Comment by nimmolo** [comment]
aha! ok. 

What if i only want to GET an array of videos where privacy.view is set to 'anybody'?

**Comment by Dashron** [comment]
I would love to support that in the future, and the way you are using it is exactly how I pictured it, but unfortunately we do not currently support that functionality.

The best way right now would be to request them, and loop through checking each privacy value.

Embeddable might  be a good solution too, it only returns videos who's privacy.embed is "anywhere" or "only on these domains". We do not currently allow you to specify a domain, but it's on the roadmap!

**Comment by nimmolo** [comment]
Aaron - Got it, thanks. I should have put the dot notation question in a different issue thread!

I'm still stuck on the original question, how to handle the comma/"%2C" conversion for field filtering. Did you find out anything about why percent encoding isn't accepted?

**Comment by Sventour** [comment]
Hi @nimmolo, 

Can you paste how are you imploding your fields array? 
The percent encoded commas for the field filter appears to be respected in the response. 

here's the working url that's generated for me: `https://api.vimeo.com/users/152184/videos?fields=name%2Clink%2Cdescription%2Cuser%2Cprivacy%2Ctags%2Crelease_time&sort=date&filter=embeddable&filter_embeddable=true`

**Comment by nimmolo** [comment]
Hi Sventour -

Here's what i'm using. I'm getting around the parameters situation by passing the imploded string directly to a modified version of the library function.

```
// Limit fields
  $fields_desired = array(
                  'uri',
                  'name',
                  'link',
                  'description',
                  'duration',
                  'pictures',
                  'user.name',
                  'user.link',
                  'privacy',
                  'tags',
                  'release_time',
                  );
  $fields_desired = implode(',', $fields_desired);


  $vimeo = new \Vimeo\Vimeo($developer_key, $secret_key, $access_token);
  $per_page = 50;
  $date = date(DATE_RSS);
  $new_videos = array();

  // loop through all feed pages
  $page = 1;
  do {
    // Do an authenticated call
    try {
      $videofeed = $vimeo->request('/users/'.$author_id.'/videos',
                                    array(//'fields' => $fields_desired,
                                          // 'privacy.view' => 'anybody',
                                          'sort' => 'date',
                                          'filter' => 'embeddable',
                                          'filter_embeddable' => 'true',
                                          'page' => $page,
                                          'per_page' => $per_page),
                                    'GET',
                                    true,
                                    $fields_desired); //nimmo hack for Vimeo library
    }

```

And here's the modification of the Vimeo.php request function:

```
    /**
     * Make an API request to Vimeo.
     *
     * @param string $url A Vimeo API Endpoint. Should not include the host
     * @param array $params An array of parameters to send to the endpoint. If the HTTP method is GET, they will be added to the url, otherwise they will be written to the body
     * @param string $method The HTTP Method of the request
     * @param bool $json_body
     * @param string $fields_desired - Comma-separated string of fields to return SPECIAL TO EXTERNAL VIDEOS PLUGIN
     * @return array This array contains three keys, 'status' is the status code, 'body' is an object representation of the json response body, and headers are an associated array of response headers
     */
    public function request($url, $params = array(), $method = 'GET', $json_body = true, $fields_desired = '')
    {
        // add accept header hardcoded to version 3.0
        $headers[] = 'Accept: ' . self::VERSION_STRING;
        $headers[] = 'User-Agent: ' . self::USER_AGENT;

        // add bearer token, or client information
        if (!empty($this->_access_token)) {
            $headers[] = 'Authorization: Bearer ' . $this->_access_token;
        }
        else {
            //  this may be a call to get the tokens, so we add the client info.
            $headers[] = 'Authorization: Basic ' . $this->_authHeader();
        }

        //  Set the methods, determine the URL that we should actually request and prep the body.
        $curl_opts = array();
        switch (strtoupper($method)) {
            case 'GET' :
                if (!empty($params)) {
                    $query_component = '?' . http_build_query($params, '', '&');
                } else {
                    $query_component = '';
                }

                $curl_url = self::ROOT_ENDPOINT . $url . $query_component;
                // NIMMO MODIFICATION APPENDS DESIRED FIELDS
                $curl_url = $curl_url . '&fields=' . $fields_desired;
                echo $curl_url . '<br />';

                break;

            case 'POST' :
            case 'PATCH' :
            case 'PUT' :
            case 'DELETE' :

// no further mods
```

Is there a way to pass the fields through the parameter args, without modifying the library function?

**Comment by Sventour** [comment]
Can you paste the encoded url that's generated without your modification to the library?

**Comment by nimmolo** [comment]
Yes - sorry for the delay

`https://api.vimeo.com/users/468130/videos?fields=uri%2Cname%2Clink%2Cdescription%2Cduration%2Cpictures%2Cuser.name%2Cuser.link%2Cprivacy%2Ctags%2Crelease_time&sort=date&filter=embeddable&filter_embeddable=true&page=1&per_page=50`
