### ISSUE TITLE
filter_embeddable user videos: Returning false even for whitelisted domains

### ISSUE THREAD

**Issue by nimmolo** [vimeo/vimeo.php#106]
I'm trying to use the vimeo.php library to check a client's Vimeo account daily for new videos, and if there are, to embed them in his own site. About half the client's videos require a password and are not intended to be embeddable, so `filter_embeddable` is necessary. The others are intended to be embeddable on his own site only.

In the client's Vimeo account, for all embeddable videos I switched the embeddable setting to `"Only on sites I choose"` and whitelisted both his domain and the relevant subdomain.

My implementation of the Vimeo.php library generates the following URL: 
`https://api.vimeo.com/users/468130/videos?sort=date&filter=embeddable&filter_embeddable=true&page=1&per_page=50&fields=uri,name,link,description,duration,pictures,user.name,user.link,privacy,tags,release_time`

This query returns 0 videos. If, back on Vimeo, I switch any video to `embeddable: anywhere`, THAT video IS returned in the data. Same for multiple videos.

This leads me to believe either the filter itself only works for `embeddable:anywhere`, the whitelist is not implemented correctly or my query is not formed correctly.

It also seems possible `filter=embeddable&filter_embeddable=true` only works for Channel queries (not User queries). Is this the case?

Testing from my development environment, without a fixed IP I don't think I can whitelist my own localhost (can I?). However with videos set to `embeddable: anywhere`, my GET call also worked locally, pulling only those videos.

**Comment by nimmolo** [comment]
It's tricky to troubleshoot this from the client side since the filtering is done on Vimeo's end. I can't tell at which point the filter is kiboshing the domain, or if the site is reporting a different domain, for example. It shouldn't be as far as I know.

**Comment by nimmolo** [comment]
Sorry about the previous phrasing of this question. Edited for clarity now!

**Comment by nimmolo** [comment]
Please update the docs!

From Tommy Penner at [Vimeo User Support:](https://vimeo.com/forums/api/topic:284004)

> Videos with domain-level privacy will not return when setting filter_embeddable=true.

**Comment by erunion** [comment]
Ah, sorry about that. We're working on rewriting all of our documentation.
