### ISSUE TITLE
Privacy setting

### ISSUE THREAD

**Issue by KrGyan** [vimeo/vimeo.php#107]
Is there any option to manage privacy settings of any video at the time of uploading or after uploading a video so that the embedded code or video can be played on only one site.

**Comment by Dashron** [comment]
At the moment you can only edit privacy settings after upload via the "Edit One Video" endpoint: https://developer.vimeo.com/api/endpoints/videos#PATCH/videos/{video_id}

In the future we plan on supporting all clip options at the time of upload, but that will still take some time.

**Comment by Dashron** [comment]
Whoops, missed the part about "only played on one site". For that you have to use the "domain" embed privacy, and add your domains via this endpoint: https://developer.vimeo.com/api/endpoints/videos#/{video_id}/privacy/domains
