### ISSUE TITLE
Bad Request when method is specified in lowercase

### ISSUE THREAD

**Issue by jimyaghi** [vimeo/vimeo.php#108]
When making a request using, say, the 'patch' method, if specified in lowercase it returns BAD REQUEST. If changed to uppercase it works. 

Fix is simple. Line 118 in Vimeo.php needs to also use strtoupper, (not just the switch/case block)

$curl_opts = array(
                    CURLOPT_POST => true,
                    CURLOPT_CUSTOMREQUEST => strtoupper($method),
                    CURLOPT_POSTFIELDS => $body
                );

**Comment by Dashron** [comment]
Nice catch, we'll get this added!
