### ISSUE TITLE
Upload problems

### ISSUE THREAD

**Issue by rafaelharus** [vimeo/vimeo.php#111]
I am making an mp4 file upload with the library in version 1.2.4 and finish uploading have the video ID, but when checking the files on Vimeo, I realize that were made simultaneously upload two or more videos ... I'm using PHP pure in own index.php

require_once('vendor/autoload.php');

$vimeoId = 'xxxxx';
$secret = 'xxxxx';
$token = 'xxxxx';

$vimeo = new Vimeo\Vimeo($vimeoId, $secret, $token);
$res = $vimeo->upload('video.mp4', false);
var_dump($res);

**Comment by cansozeri** [comment]
Same over here, Uploads two video, one of them has no title but the video is ok. One of them has got title but the video status is still uploading. What is this ????

**Comment by Dashron** [comment]
Thanks for the reports, we're looking into it!

**Comment by rafaelharus** [comment]
It seems that now the problem is solved :))

**Comment by cansozeri** [comment]
Thanx, I am gonna try ...


Samsung Mobile tarafından gönderildi.


-------- Orjinal mesaj --------
Kimden: Rafael Harus
Tarih:10 10 2016 22:34 (GMT+02:00)
Alıcı: "vimeo/vimeo.php"
Cc: cansozeri , Comment
Konu: Re: [vimeo/vimeo.php] Upload problems (#111)


It seems that now the problem is solved :))

-

**Comment by Dashron** [comment]
Let me know if you still see the problem. We made some changes, but continue to investigate the cause of the problem.

**Comment by cansozeri** [comment]
@Dashron the situation is worse now, I got time out exception .. Can not load anythnig ..

**Comment by cansozeri** [comment]
@Dashron Very interesting I have got time-out error, but on site there is a video uploaded, but with no title. But I can not get a response, so I can not got the id or anything.. But the video is there with untitled. 

https://vimeo.com/186492111

**Comment by Dashron** [comment]
@cansozeri I believe the timeout might be a different issue. We'll take a look.

**Comment by cansozeri** [comment]
@Dashron it seems working now : =) Thanx ..
