### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by Spudley** [vimeo/vimeo.php#113]
I am raising this issue to make a suggestion that unit tests be written for this class.

I would always be happier to trust a class that has tests written for it. However I note that there may be a need to refactor some of the code first in order to make it easier to write the tests.

**Comment by Dashron** [comment]
I totally agree. Unit tests are on our radar and will be part of an upcoming release!

**Comment by peter279k** [comment]
Before doing the unit testing, I think the package need to be unified code style.

For example, the method of declaring variable name is very awful.

**Comment by erunion** [comment]
@peter279k Example in particular?

**Comment by peter279k** [comment]
Hi @erunion, thank you for your problem.

I  create a[ PR ](https://github.com/vimeo/vimeo.php/pull/116)and we can refer this.

Thanks.

**Comment by erunion** [comment]
I set up StyleCI and TravisCI with some initial and very basic tests to verify that the library doesn't completely fail over on the PHP versions we say it should run on.

As real unit tests are definitely on our radar, I'm going to close this out.
