### ISSUE TITLE
JSON request does not return videos in channel order

### ISSUE THREAD

**Issue by Lhari** [vimeo/vimeo.php#119]
Custom sort order has been set up on channel, however, this is not returned in the feed, is there anything I'm missing, or has this simply not been done?

**Comment by Dashron** [comment]
The sort parameter "default" will sort videos by the user-selected default. If you do not provide a sort parameter it will always sort by "date".

We will be improving the wording and documentation of these parameters in an upcoming release.

Let me know if the above solves your issue!

**Comment by Lhari** [comment]
That's all well and good, but the default sort parameter from the channel does not seem to be transfered correctly, below this, I have linked the the channel, and the display page, for which I'm using the Vimeo API, and the sort parameter does not get applied correctly. The only thing I'm doing is: Request channel from Vimeo, save request in .json, call json to to iterate over.

https://vimeo.com/channels/1073630/page:1
https://www.gloster.com/gle/mediapage

As evident on those two, they are not sorted in the same order.

**Comment by Dashron** [comment]
Can you provide me with an example API call that is sorting incorrectly, including the URL and any query string parameters?

**Comment by Lhari** [comment]
$vimeoContent = '/channels/'.$vimeoIdValue.'/videos';
$o = $vimeo->request($vimeoContent, 'GET');

If I add a sort filter like playground, so my code looks like this:
$vimeoContent = '/channels/'.$vimeoIdValue.'/videos?sort=default';
or:
$vimeoContent = '/channels/'.$vimeoIdValue.'/videos?sort=manual';

I get the following response:

`
Array
(
    [body] => Array
        (
            [error] => The sort provided is not valid for this resource.
        )

    [status] => 400
)
`
Followed by a Header, without an videos within it.

**Comment by Dashron** [comment]
Glad to hear! Let us know if you have any more issues, or if you found anything particularly confusing. I would love to make sure users don't run into this same issue again!
