### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by sfatfarma** [vimeo/vimeo.php#122]
Hello, sorry for the issue opening, but I did not knew how to contact you elsewhere. My question is that which is the minimum PHP version required for this framework to work? I haven't found it specified anywhere. Thanks!

**Comment by erunion** [comment]
@sfatfarma The minimum PHP version for the library is [PHP 5.3](https://github.com/vimeo/vimeo.php/blob/master/composer.json#L15).

**Comment by sfatfarma** [comment]
@erunion Thank you very much.
