### ISSUE TITLE
Check user upload quota

### ISSUE THREAD

**Issue by anuj9196** [vimeo/vimeo.php#125]
Is there a way to check for user quota before uploading. If not please add this functionality.

**Comment by Dashron** [comment]
Our upload guide explain this in more detail: https://developer.vimeo.com/api/upload/videos#check-quota! Let me know if you have any further questions

**Comment by anuj9196** [comment]
I tried
```
$http = new Client();
$res = $http->get('https://api.vimeo.com/me', $this->access_token);
debug($res);
```

Where `$this->access_token` is the access token of user and is working for video uploading.

But this gives error as
```
code => (int) 401
reasonPhrase => 'Authorization Required'
```

**Comment by Dashron** [comment]
`Client()` does not appear to be part of this PHP library. What HTTP request library are you using?

In this library, the access token is assigned to the Vimeo library using the `setToken` method. You can see an example at the end of "Authenticated Requests" docs: https://github.com/vimeo/vimeo.php#authenticated.

Outside of this library, you use the `Authorization` header as described here: https://developer.vimeo.com/api/authentication#making-requests

**Comment by anuj9196** [comment]
I'm using `http client` of cakephp 3 to make post request, as it is given in documentation to make a post request to get quota of user. 

Is there some predefined function in this library ? I couldn't find one.

**Comment by Dashron** [comment]
There isn't a "get quota" function, but you should use the [request method](https://github.com/vimeo/vimeo.php#make-requests) along with our [upload quota docs](https://developer.vimeo.com/api/upload/videos#check-quota)
