### ISSUE TITLE
Get MP4 for public videos

### ISSUE THREAD

**Issue by no1youknowz** [vimeo/vimeo.php#127]
I'm trying to replicate something like this:

https://codepen.io/mattgrosswork/pen/jrdwK

I have the client_id, secret and access token.  Is there anyway I can get the MP4 url of any video from oembed?

Right now, I'm able to replicate this effect with the player, but there is a flash of the controls first and I want to get rid of this, as it feels a bit hacky.

Of course, I wouldn't have this problem if I could hide the controls.  But that's not going to happen any time soon. I have read.

Thanks

**Comment by erunion** [comment]
Send an email to our support team, https://vimeo.com/help/contact#tech-api, and they can work with you.

**Comment by lavallette90** [comment]
I'm using this [website](https:www.vimeotomp4.com/) to download vimeo to mp4..Might be helpful for you.
