### ISSUE TITLE
Get direct video url

### ISSUE THREAD

**Issue by shanka12** [vimeo/vimeo.php#128]
How do I get vimeo video direct url without player.vimeo.com/... ?

**Comment by Dashron** [comment]
If your API request meets the following conditions you should see video files under the `files` key of any video response. These responses are returned from API calls such as GET /me/videos

- If you are using an access token authenticated to a user
- If that user created the API application making the API request
- If the video you are accessing is owned by that user
- If that user is PRO or Business tier

If you do not see those files reach out to us at vimeo.com/help/contact

**Comment by erunion** [comment]
@heldchen Can you send an email into our support team? They should be able to sort you out. https://vimeo.com/help/contact

**Comment by heldchen** [comment]
@erunion I already did - it is a documentation bug. sometimes between 3.2 and 3.4 the additional scope `video_files` was added but not documented in the api changelog (https://developer.vimeo.com/api/changelog). new auth tokens need to be created with the new scope added.

**Comment by erunion** [comment]
Ah, gotcha. Yeah our changelog doesn't show scope changes right now unfortunately. It's on my giant list of things to do before the year's out though.
