### ISSUE TITLE
Upload info

### ISSUE THREAD

**Issue by Fanda36** [vimeo/vimeo.php#131]
Hi,

I'm making app for upload videos via form. I use for this "Simple HTTP POST uploading":
`$resp = self::$lib->request('/me/videos', array('type' => 'POST', 'redirect_url' => $redirectUrl), 'POST');`

Upload work, the video is created, but I have problem with check upload state.
After few second I'm testing state, if video is uploadet:
`$status = self::$lib->request($resp['body']['uri']);`

Response for `$resp['body']['uri'] = /users/user696xxxxx/tickets/d53eddaa3538125f77e7a7a3f4afbb58` is:
```
$status = array(3) {
  | ["body"]=>
  | NULL
  | ["status"]=>
  | int(204)
  | ["headers"]=>
  | array(18) {
  | ["Server"]=>
  | string(5) "nginx"
  | ["Content-Type"]=>
  | string(24) "text/html; charset=UTF-8"
  | ["Cache-Control"]=>
  | string(27) "no-cache, max-age=315360000"
  | ["Strict-Transport-Security"]=>
  | string(44) "max-age=15552000; includeSubDomains; preload"
  | ["X-RateLimit-Limit"]=>
  | string(3) "100"
  | ["X-RateLimit-Remaining"]=>
  | string(2) "98"
  | ["X-RateLimit-Reset"]=>
  | string(25) "2017-08-08T22:20:21+00:00"
  | ["Expires"]=>
  | string(29) "Fri, 06 Aug 2027 22:05:21 GMT"
  | ["Via"]=>
  | string(11) "1.1 varnish"
  | ["Fastly-Debug-Digest"]=>
  | string(64) "c31ca9aded934b923235ae1055f8a7d98655efc4afadbeaf193677ba702d7054"
  | ["Accept-Ranges"]=>
  | string(5) "bytes"
  | ["Date"]=>
  | string(29) "Tue, 08 Aug 2017 22:05:21 GMT"
  | ["Connection"]=>
  | string(10) "keep-alive"
  | ["X-Served-By"]=>
  | string(36) "cache-iad2135-IAD, cache-ams4426-AMS"
  | ["X-Cache"]=>
  | string(10) "MISS, MISS"
  | ["X-Cache-Hits"]=>
  | string(4) "0, 0"
  | ["X-Timer"]=>
  | string(28) "S1502229922.672537,VS0,VE106"
  | ["Vary"]=>
  | string(38) "Accept,Vimeo-Client-Id,Accept-Encoding"
  | }
  | }
```
Why I get null response?
Is any way to get video id from ticket (from API)?

Thanks.

**Comment by erunion** [comment]
Hi there, so this is a problem on our end with us having bad documentation. The `/users/:id/tickets/:ticketid` endpoint is only supposed to let you know if a upload ticket exists in our system or not, via a `204 No Content` HTTP code.

For the next version of our API, we're working on having that endpoint return a full response with information about the video, the user who uploaded it, and a few other things. We currently do not have an ETA for this release.
