### ISSUE TITLE
Unable to upload video sometimes

### ISSUE THREAD

**Issue by vishalmandora** [vimeo/vimeo.php#132]
Sometimes unable to upload video on my vimeo pro account. what's the issue?
no errors. no blockages still don't get response.

**Comment by vishalmandora** [comment]
![screenshot from 2017-08-11 09-59-49](https://user-images.githubusercontent.com/22556281/29201485-46d92478-7e7c-11e7-9c1a-fc4ff6cf0272.png)


Unable to complete request. [Connection timeout after 30001 milliseconds] in app/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php:156.
Can you please explain why does this happen?

**Comment by erunion** [comment]
Hey @vishalmandora, this doesn't appear to be an issue with our PHP library. If you submit a ticket to our support team, they should be able to sort out what the problem is. 

https://help.vimeo.com/hc/en-us/requests/new
