### ISSUE TITLE
How do you upload a video directly to Vimeo's servers (bypassing your own server)

### ISSUE THREAD

**Issue by larelb** [vimeo/vimeo.php#133]
Before this ticket is closed with redirecting me to [here](https://developer.vimeo.com/api/upload/videos#simple-upload), can you ACTUALLY explain the process of uploading a video directly to Vimeo? I am using Laravel 5.4, and I am familiar with [Vinkla's](https://github.com/vinkla/laravel-vimeo) wrapper, but I already asked him the question and he closed it immediately while redirecting me here. 

I am mainly confused because my form has other details linking to an action that processes all of the information. The Vimeo API guide's example shows an action in an upload form linking to a _**upload_link_secure**_ URL, but I don't see how I can actually upload the file without changing my action to what they suggest. I just want to process the upload in my own controller action after the form submit button is clicked.

**Comment by Dashron** [comment]
There are two ways for an end user to upload a video to vimeo via your site. One sends the data from the browser directly to vimeo, the other sends the data from your server directly to vimeo (and the user has to get the video into your service somehow).

When you say "I just want to process the upload in my own controller action after the form submit button is clicked." what type of controller are you talking about? Are you talking about a JavaScript controller in the browser, or a backend controller on your server?

**Comment by larelb** [comment]
Thanks for the reply. I'm referring to a backend controller in Laravel (Php).

Sent from Blue<http://www.bluemail.me/r?b=10455>
On Sep 1, 2017, at 9:14 PM, Aaron Hedges <notifications@github.com<mailto:notifications@github.com>> wrote:

There are two ways for an end user to upload a video to vimeo via your site. One sends the data from the browser directly to vimeo, the other sends the data from your server directly to vimeo (and the user has to get the video into your service somehow).

When you say "I just want to process the upload in my own controller action after the form submit button is clicked." what type of controller are you talking about? Are you talking about a JavaScript controller in the browser, or a backend controller on your server?

**Comment by Dashron** [comment]
We have an example of that here: https://github.com/vimeo/vimeo.php#upload-videos-from-the-server. The file should be a path to the file on your server (php has docs on their file upload system here: http://php.net/manual/en/features.file-upload.post-method.php).

Let me know if you need more help and I can respond after this plane lands :)

**Comment by larelb** [comment]
So, how do I upload from the browser?

**Comment by erunion** [comment]
There currently isn't a way to passthrough anything from a `$_FILES` global to our servers from this library right now, so if you would want to have your own form and controller for uploading, you'd have to temporarily store that file on your server, and then use the `upload` method that @Dashron linked to pass it along to us.

**Comment by erunion** [comment]
You *might* be able to get away with passing `$_FILES['tmp_name']` into `upload`. Your mileage may vary, though.

**Comment by larelb** [comment]
For those of you wondering, I was able to use erunion's advise and upload the $request->file object. I passed that right into the upload call.

**Comment by erunion** [comment]
Awesome, glad to hear you got it sorted out.

**Comment by nishadhasan** [comment]
I need a way to upload the video directly to Vimeo from my website. Can you please suggest me a good way where I don't need to upload the video first on my server? TIA

**Comment by tommypenner** [comment]
@nishadhasan The usecase you describe is best served by the "Pull" upload method, where Vimeo's upload server will pull a video file from a specified URL on the open internet, and "upload" it to Vimeo. The method is documented here: https://developer.vimeo.com/api/upload/videos#pull-upload

**Comment by nishadhasan** [comment]
But I need a upload the videos directly to Vimeo. The present situation is, I am uploading the videos on my server first then it goes to the Vimeo. It takes twice the time to go to Vimeo, which is very bad. I need a solution where I can send the videos directly to Vimeo from my website without storing videos on my server first. is there any solution for that?

**Comment by erunion** [comment]
@nishadhasan The `post` method might work for you in that case. That'll give you an HTML form for your user to upload the video to.

https://developer.vimeo.com/api/upload/videos#form-upload
https://developer.vimeo.com/api/upload/videos#form-based
