### ISSUE TITLE
Error requesting access token

### ISSUE THREAD

**Issue by Vshri** [vimeo/vimeo.php#134]
I have a error : "405 method not allowed" when  request to https://api.vimeo.com/oauth/access_token,

var redirectURL =   window.location.protocol + 
                            '//' + window.location.hostname + 
                            window.location.pathname +
                            '?cmd=vimeo-token-form';
        
        var baseIdSecret = 'basic ' + btoa(_clientId + ":" +_clientSecret);  
        $.ajax({
            type        : "POST",
            url         : "https://api.vimeo.com/oauth/access_token",
            ContentType :'application/x-www-form-urlencoded',
            headers     : {"Authorization" : baseIdSecret},
            data        : {
                'grant_type'   : 'authorization_code',
                'code'         : _code,
                'redirect_uri' : redirectURL,
            },
            success     : function(_result){
                        console.log("SUCCESS"+_result);

            error       : function(_result){
                console.log(_result);

Tested same request in **postman** and the result is **error :"error while sending request: Failed to execute 'setRequestHeader' on 'XMLHttpRequest:Basic zja4j*************8==' is not a valid Http header file".**

If header is removed the result is
 **"error":"invalid_client",
"error_description":"A valid client ID must be provided along with any request made to Vimeo's API"**

Please help me out,
Thanks!

**Comment by Dashron** [comment]
I'm not terribly familiar with JQuery's ajax method, and this issue tracker is for the php library. I think you will find a much more knowledgeable pool of experts over at stackoverflow.com!

**Comment by Vshri** [comment]
but $lib->accessToken($code, $redirecturi);

**Comment by Vshri** [comment]
I Also tried this   
try {    
            $config     = Rialbase_Core::getConfig();
            $fbConfig   = $config->vimeo;
            
            $ch = curl_init();
            curl_setopt($ch, CURLOPT_HTTPHEADER, ("Authorization :".  base64_encode($fbConfig->client_id.":".$fbConfig->client_secret)));
            curl_setopt($ch, CURLOPT_URL,"https://api.vimeo.com/oauth/access_token?grant_type=authorization_code&code=".$_code."&redirect_url=".$_redirectURL);
            curl_setopt($ch, CURLOPT_CUSTOMREQUEST,"POST");
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);//
            curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
            $res = curl_exec($ch);
            
            return $res;
            
        } catch (Exception $ex) {            
            throw $ex;
        }
    }
    
same error again
"error":"invalid_client",
"error_description":"A valid client ID must be provided along with any request made to Vimeo's API"

**Comment by Dashron** [comment]
In the above PHP code I see two issues.

First, there needs to be a space between the Colon and the header contents. Second you need to describe the token type in the authorization header. Our tokens are "Bearer" tokens. I have updated your authorization header code below

`curl_setopt($ch, CURLOPT_HTTPHEADER, ("Authorization : Bearer ".  base64_encode($fbConfig->client_id.":".$fbConfig->client_secret)));`

**Comment by Vshri** [comment]
Thanks for your response, 

I have made changes as suggested by you but the same problem persist again,

"error":"invalid_client",
"error_description":"A valid client ID must be provided along with any request made to Vimeo's API"
