### ISSUE TITLE
Trying to upload video

### ISSUE THREAD

**Issue by IndiAsh** [vimeo/vimeo.php#137]
A few days ago i was able to upload video to my vimeo account. 
Today i tried to do the same thing and i got the following error.

Uncaught exception 'Vimeo\Exceptions\VimeoRequestException' with message 'Unable to complete request.[OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 1512435598.cloud.vimeo.com:443 ]' in /home/domain/libs/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php:156
--
  | Stack trace:
  | #0 /home/domain/libs/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(405): Vimeo\Vimeo-&gt;_request('https://1512435...', Array)
  | #1 /home/domain/libs/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(322): Vimeo\Vimeo-&gt;perform_upload('/home/do...', Array)
  | #2 /home/domain/assets/website/upload/video.tmp.php(290): Vimeo\Vimeo-&gt;upload('/home/do...', false)
  | #3 /home/domain/assets/website/category.tpl.php(72): include('/home/do...')
  | #4 /home/domain/site_functions.php(51): include('/home/do...')
  | #5 /home/domain/init.php(231): Template('category.tpl.ph...', 0)
  | #6 /home/domain/in in <b>/home/domain/libs/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php

My Code
try {
    $uri = $lib->upload($file_name, false);
    $video_data = $lib->request($uri);
    print_r($video_data);
} catch (VimeoUploadException $e) {
    //  We may have had an error.  We can't resolve it here necessarily, so report it to the user.
    print 'Error uploading ' . $file_name . "\n";
    print 'Server reported: ' . $e->getMessage() . "\n";
}

**Comment by erunion** [comment]
Have you tried again since you experienced this error on Friday? It looks like we may have had some hiccups on our upload service.

**Comment by jaap** [comment]
Yes, seems to be working again…

**Comment by erunion** [comment]
Cool, sorry about that.

**Comment by jaap** [comment]
Sorry @erunion . I replied to the Github mail since I was following this issue but was also in contact with Vimeo support (and mentioned this issue), so @IndiAsh should still confirm...
