### ISSUE TITLE
Is there any webhook to get notified after videos have uploaded?

### ISSUE THREAD

**Issue by shigg1120** [vimeo/vimeo.php#138]
First of all, thanks for the package. It's amazing.

I let my users upload a video on my web app. When users upload a video, I move the video to a folder and then upload it to Vimeo using `$response = $lib->upload('/video.mp4', false)`.

It works great but the thing is I need to store a thumbnail url in the database but when I dump 
```
$response = $lib->upload('/videos.mp4', false);
dump($lib->request($response));
```

`pictures` is null since the video is still being uploaded to Vimeo. What's the workaround for this?

Is there any webhook to get notified after videos are uploaded onto Vimeo, so I can get the processed thumbnail urls for the uploaded video by `$lib->request('video-url')`?

**Comment by erunion** [comment]
We do not currently support webhooks. `$lib->upload()`, when successful, should return an API URI that you can query to get a full video representation.

**Comment by shigg1120** [comment]
Thanks. I asked this on the Vimeo forum, but is the only workaround to guesstimate if videos have processed and perform a get request to get information of the uploaded video? Is there any best practice for this?

**Comment by erunion** [comment]
I'm not sure I follow 100%. `$lib->upload` does its uploading synchronously, so to find out if a video was processed, you can just wait for it to return a response.

**Comment by shigg1120** [comment]
Yes I use this `$lib->upload` to upload a video. But, it takes some time for uploaded videos to be processed.

For example, the `pictures` key is null when getting a response after sending a video by `$lib->upload` . And, we have to wait to get a thumbnail url to be available. That's why I asked this.

>is the only workaround to guesstimate if videos have processed and perform a get request to get information of the uploaded video? Is there any best practice for this?

**Comment by erunion** [comment]
Oh I see now. If `pictures` is null still while we're still processing it post-upload, you can periodically query the video with a [JSON filter](https://developer.vimeo.com/api/common-formats#json-filter) of `?fields=pictures,status`. 

If `status` is `available`, then the video is fully processed, `pictures` should no longer be null and you can use that right away.

Using a JSON filter on this will minimize the impact your app will see with regard to our rate limits.

**Comment by shigg1120** [comment]
Thanks for your help

**Comment by erunion** [comment]
Of course!
