### ISSUE TITLE
Can't pull video using api  from google drive or post two videos in same time !

### ISSUE THREAD

**Issue by Deve1234** [vimeo/vimeo.php#139]
Hi ,
I couldn't use the pull method for my API , every time I tried that the pull video from google drive or any other source it's  shown at vimeo dashboard as corrupted and his Duration 00:00, 

![error](https://user-images.githubusercontent.com/32922041/31756664-d24923e8-b4ad-11e7-9519-8520140f02d2.PNG)

also , if I use POST method for uploading videos , 
and I upload two videos in same time the result will be like this >
- I get response as "uploaded successfully"
- no video uploaded actually!
and I didn't get any errors or  exception back !!
any help please !

**Comment by erunion** [comment]
Hey @Deve1234, you should contact us through here https://vimeo.com/help/contact#tech-api.

Someone from our support team will be able to help you out.

**Comment by Deve1234** [comment]
I did !
#3431387
It's seems no one there !

**Comment by tommypenner** [comment]
One of our support agents will be replying to you shortly.

**Comment by Deve1234** [comment]
I can't find any reply button ! and there is no clickable button or something .
can you help me to replay on this tickets ?
#3431387

**Comment by tommypenner** [comment]
You'll need to check the email associated with your Vimeo account. Support is initiated through the contact form, and the help center will report the status of your support ticket in our system, but ongoing communication is handled via standard email.

**Comment by Deve1234** [comment]
what is the support's email ?
