### ISSUE TITLE
How do I Add Video to a Channel

### ISSUE THREAD

**Issue by LGRAssociates** [vimeo/vimeo.php#141]
I wrote an application to do batch uploads to vimeo it works perfect except I can't figure out how to add an uploaded video to an existing channel. 
The actual Title of channel is "School Board Meetings 2017-1018" My channel id is vimeo.com/channels/1310177 which I got from the Channel->Settings on the web site.

The variable $putInChannel below contains the string "/channels/1310177/videos/240167627"

The video uploads fine but still is not added to the channel.

Here is a snippet of my code, the last line is the problem.

$lib = new Vimeo($client_id, $client_secret, $accessToken);
$uri = $lib->upload($fileTempName);
$lib->request($uri, array('name' => $fileName), 'PATCH');
$lib->request($uri, array('description' => $description), 'PATCH');
$putInChannel = '/channels/1310177' . $uri;
$lib->request($uri, $putInChannel, 'PUT');

**Comment by erunion** [comment]
What's the response and status code you're getting back from the `PUT` to `/channels/1310177/videos/240167627`?

**Comment by LGRAssociates** [comment]
Thanks for your reply.  I have not tried the PUT function because I can't find any code example.  PUT is not a PHP function so do I have to write my own using curl? How would I authenticate?  ---------- Original Message ----------

**Comment by LGRAssociates** [comment]
I downloaded the httpful from https://github.com/nategood/httpful
I then modified an example and created a test php script:

    <?php
    require(__DIR__ . '/../bootstrap.php');
    use \Httpful\Request;

    $uri = 'https://api.vimeo.com/channels/1310177/videos/240167627';
    $request = Request::put($uri)->send();
    echo $request;

The Request returned:
    { "error": "You must provide a valid authenticated access token." }

So obviously I need to know where and how to pass this access token?

**Comment by erunion** [comment]
I'm not familiar with that library, but you'd need to pass the access token through a bearer `Authorization` header. See our authorization documentation here: https://developer.vimeo.com/api/authentication#making-requests

If you need further support not related to our PHP SDK, please email our support team through https://developer.vimeo.com/help
