### ISSUE TITLE
buildAuthorizationEndpoint issue

### ISSUE THREAD

**Issue by radomirklacza** [vimeo/vimeo.php#145]
To build auth endpoint (buildAuthorizationEndpoint()) you are using 
$query = array(
            "response_type" => 'code',
            "client_id" => $this->_client_id,
            "redirect_urI" => $redirect_uri
        );
which throw an error on vimeo site saying the redirect_url was not set. In order to fix one need to replace redirect_urI (capital 'i') with  redirect_url (small "L"). Then it works :)

**Comment by erunion** [comment]
Are the contents of `$redirect_uri` set as your callback URL in your API app settings? We actually look for `redirect_uri` in our server code, and if that matches it's good, but if it's not present, we just use the configured callback URL on your app.
