### ISSUE TITLE
A valid client ID must be provided along with any request made to Vimeo's API

### ISSUE THREAD

**Issue by TaktakTaktouk** [vimeo/vimeo.php#147]
Hi I get "A valid client ID must be provided along with any request made to Vimeo's API" error when I try to request an access token using my application.
I used the same code in this [example](https://github.com/vimeo/vimeo.php/blob/master/example/auth.php) 
Here is [my app on Vimeo](https://developer.vimeo.com/apps/118480) if you want to check if I forget something:

**Comment by tommypenner** [comment]
We'll need to see your client_id and your specific implementation of the code. Can you email us (and reference this GitHub Issue)? Use the Contact form here: https://vimeo.com/help/contact

**Comment by TaktakTaktouk** [comment]
Yes, I did! please check your help center

**Comment by Ury18** [comment]
Any information on this? It's happening to me and I am using Exrpess.js. I am getting the following message in the response body: 
```json
{
  error: 'invalid_client',
  error_description: 'A valid client ID must be provided ' +
    "along with any request made to Vimeo's " +
    'API'
}
```

**Comment by erunion** [comment]
@Ury18 Contact the support team at https://vimeo.com/help/contact. They should be able to help you out better than here.

**Comment by Ury18** [comment]
I did but it's been 2 days and still no answer from them.

**Comment by Ury18** [comment]
Is there any fast way to contact vimeo support? I've been stuck with this for a week and I still got no answer, quite annoying frankly.

**Comment by erunion** [comment]
// @tommypenner @onebrownsound
