### ISSUE TITLE
Delete Uploaded Video

### ISSUE THREAD

**Issue by Mr-Anonymous** [vimeo/vimeo.php#148]
Similar to `$lib->upload('/home/aaron/Downloads/ada.mp4')`, is there a method to delete an already uploaded video from the Vimeo server? Something like:
```
$lib->delete('/home/aaron/Downloads/ada.mp4')
```

**Comment by erunion** [comment]
Yes, if you have the URI of a video you can pass it to `$lib->request()`:

```php
$uri = '<your Vimeo video URI>'; // example: `/videos/1234`
$lib->request($uri, [], 'DELETE');
```

https://developer.vimeo.com/api/endpoints/videos#DELETE/videos/{video_id}

**Comment by Mr-Anonymous** [comment]
Thank you @erunion That helps heaps.
