### ISSUE TITLE
pull upload issue (upload from server url)

### ISSUE THREAD

**Issue by yasirrose** [vimeo/vimeo.php#149]
Thanks for building this nice API for Vimeo. 

I am facing a issue when i upload video through web url. I am using following line of code:
`$response = $lib->request('/me/videos', ['type' => 'pull', 'link' => $videowebpath], 'POST');`

The file is uploading but when i see the video on vimeo. It is saying:
**Invalid file
There was a problem with the file you tried to upload.**

If i upload the same file using upload function. It works fine on vimeo also. Here is the code: 
`$uri = $lib->upload($absolutepath);`

I really want to make it work through pull uploads. Can any one let me know what could be the issue.

**Comment by tommypenner** [comment]
To troubleshoot further, we'll need the link value you're providing to the API. Log into your Vimeo account and contact us at the link below (reference this GitHub issue and your StackOverflow post).

https://vimeo.com/help/contact

**Comment by yasirrose** [comment]
ok. just send the link and details
