### ISSUE TITLE
Video upload size

### ISSUE THREAD

**Issue by dntnikolai** [vimeo/vimeo.php#150]
I cant seem to make the api accept files that are over 2GB.
What is the recomended way to upload a big file to vimeo via the API.
I have tried to mod the code to avoid the 32bit limitations of PHP, and all the casts to int.
But I can not make it work, I'm guessing there is a better way ?

**Comment by tommypenner** [comment]
What errors do you receive back when attempting to upload over 2GB?

Do you have a Plus, PRO, or Business account? If so, do you have at least 2GB remaining in your weekly quota?

Note that Basic users are limited to uploading 500mb/week with a 5GB lifetime cap.

**Comment by dntnikolai** [comment]
Hi thanks for responding. We have a Business account, so there is room.
I have investigate the issue, and it is not a vimeo api issue per se. It has to do with int overflowing, as it is 32bit (on many systems). So maybe some safty checks would be good.
So first the filesize overflows to -2147483648 or something. Then fseek will fail once you go over 2GB etc,etc. I think I might be able to get around it though.

**Comment by markvdlaan** [comment]
@dntnikolai Hi, did you have a solution for this problem?
