### ISSUE TITLE
Unable to complete request

### ISSUE THREAD

**Issue by mtarlan** [vimeo/vimeo.php#151]
Fatal error:  Uncaught exception 'Vimeo\Exceptions\VimeoRequestException' with message 'Unable to complete request.[SSL certificate problem: unable to get local issuer certificate]' in /home/****/public_html/vimeo/src/Vimeo/Vimeo.php:449
Stack trace:
#0 /home/****/public_html/vimeo/src/Vimeo/Vimeo.php(133): Vimeo\Vimeo->_request('https://api.vim...', Array)
#1 /home/***/public_html/vimeotest.php(13): Vimeo\Vimeo->request('/me/videos', Array, 'GET')
#2 {main}
  thrown in /home/***/public_html/vimeo/src/Vimeo/Vimeo.php on line 449

**Comment by tommypenner** [comment]
Do you have the root CA added to your server?

**Comment by mtarlan** [comment]
Oh sure.   Cpanel server

**Comment by iambasitali** [comment]
@mtarlan  Can you please guide me how you fixed the issue???
I still facing the same issue.
