### ISSUE TITLE
My request output is different then the vimeo playground 

### ISSUE THREAD

**Issue by CambridgePark** [vimeo/vimeo.php#154]
From the example code I make the following:

 $video_results = $lib->request('/me/videos', array(
        'sort' => 'date',
        'direction' => 'asc'));
What I don't get is the  "download": [ ] array with actual links. The vimeo playground using the same call does return the download links.

**Comment by CambridgePark** [comment]
I have filled out the config.json with all the required auth data and see it being set in the call to $lib = new Vimeo($config['client_id'], $config['client_secret'], $config['access_token']);

**Comment by tommypenner** [comment]
To troubleshoot this issue we need some private info from you (account links, app client_id, etc.) can you contact support with your issue? Thanks.

https://vimeo.com/help/contact
