### ISSUE TITLE
PHPDoc comment for method `request` doesn't contain all the necessary `@throws` tags

### ISSUE THREAD

**Issue by darkbluesun** [vimeo/vimeo.php#155]
Because it doesn't specify what kind of errors it might throw, it's difficult to catch them properly.

Apparently it's just a VimeoRequestException that it can throw, but that should be documented.

**Comment by erunion** [comment]
Want to submit a pull request?

**Comment by erunion** [comment]
Resolved in https://github.com/vimeo/vimeo.php/commit/9559af92544db33acb6d9a78d8eddadfc938e03b.
