### ISSUE TITLE
HTTP proxy support

### ISSUE THREAD

**Issue by MichalMMac** [vimeo/vimeo.php#156]
Hello,

is it possible to configure HTTP(S) proxy url and port?

I am no php programmer but after skimming through code I don't see a way.
Is it something that would be easy to implement by you or is it up to us to look into it and come with PR?

**Comment by erunion** [comment]
Right now it is not. How do you want to utilize a proxy?

**Comment by MichalMMac** [comment]
We have a security requirement in our network environment for all connections initiated by web backend (php code) to go through HTTP proxy server for purpose of monitoring and filtering out connections from compromised web sites.

**Comment by erunion** [comment]
Ah ok, so it should be pretty easy to add in proxy support.

* Add a `setProxy` method where you could specify a new root URL.
* Update instances of `ROOT_ENDPOINT` and `AUTH_ENDPOINT` to use that proxied base URL if present.
* Maybe stop supplying `CURLOPT_CAINFO` to cURL requests if the proxy is present. 

If you're willing to make the changes, I'd gladly pull it in.

**Comment by MichalMMac** [comment]
Checkout PR #161

I decided to use array `CURL_DEFAULTS` to configre CURL proxy opts with new `setProxy()` method. `_curl_opts` array could be more appropriate but whole array may be replaced with the new one if `setCURLOptions()` is called.

btw `setCURLOptions` method could be used to configure proxy without my PR but it is missing in *Merge the options* in `uploadImage()` and `uploadTexttrack()` methods. `setProxy()` is also probably more straightforward for users to use than configuring CURL options directly.

**Comment by erunion** [comment]
Tagged to 2.0.2. Thanks!
