### ISSUE TITLE
API not returning "files"

### ISSUE THREAD

**Issue by picooose** [vimeo/vimeo.php#157]
Hi there,

I am trying to get access to my videos mp4 files but the "Files" data seems to be missing from the API response. I am a PRO user and the Node library with the same credentials seems to return all the data I need. Here's the basic code I use.

```
$vimeo_id   = "###";
$vimeo_secret = "###";
$vimeo_token  = "###";
$video_id  = "###";

$vimeo      = new \Vimeo\Vimeo($vimeo_id, $vimeo_secret, $vimeo_token);
$response = $vimeo->request('/me/videos/'.$video_id, [], 'GET');
//$response = $vimeo->request('/videos/'.$video_id, [], 'GET'); // returns the same
```

Can anyone tell me what am I doing wrong here? Any help appriciated.

**Comment by erunion** [comment]
To troubleshoot further, we'll need the access token and the video ID you're using for this request. Log into your Vimeo account and contact us at the link below (and reference this GitHub issue).

https://vimeo.com/help/contact

**Comment by picooose** [comment]
Cheers will take it from there.

**Comment by marcing** [comment]
I am having the same issue after migrating to 2.0, also PRO user. Why no answer here?!?

**Comment by erunion** [comment]
@marcing We have lot of business logic surrounding surfacing video files in the API, and the only way to accurately debug what's going on is by obtaining the access token you're using to make the request. 

Please contact our support team at https://vimeo.com/help/contact and they can help you out.

**Comment by marcing** [comment]
Dear Erunion,

I already did - thank you.
Nontheless I think you should write in changelog that 2.0 is not BC.

For me it seems that authentication does not work anymore with:
```
 Vimeo\Vimeo($apiConfig->clientId, $apiConfig->clientSecret, $apiConfig->accessToken)
```

Cheers
