### ISSUE TITLE
Undefined variable: curl_url in /vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php on line 133

### ISSUE THREAD

**Issue by fernandoval** [vimeo/vimeo.php#158]
This error is caused when the function request is executed by line 571.

```
$verify_response = $this->request($url, array(), 'HEAD');
```

There is no 'HEAD' condition in the switch, then the variable is not created.

**Comment by jzeisloft** [comment]
I am experiencing the same problem.  There is no "HEAD" case in the switch statement in the request() function to define the $curl_url.

**Comment by erunion** [comment]
`HEAD` support has been added into v2.0.1.
