### ISSUE TITLE
Update upload example

### ISSUE THREAD

**Issue by thomasaull** [vimeo/vimeo.php#159]
The example for the pull upload seems outdated: https://github.com/vimeo/vimeo.php#upload-videos-from-a-url

The url parameter needs to be inside the upload parameter, according to the API documentation: https://developer.vimeo.com/api/upload/videos#using-the-pull-approach

Working example would be:

```php
$video_response = $lib->request(
    '/me/videos',
    [
        'upload' => ['approach' => 'pull', 'link' => $url]
    ],
    'POST'
);
```

**Comment by erunion** [comment]
Oops sorry about that. Fixed.
