### ISSUE TITLE
Undefined index: Range in /vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php:532

### ISSUE THREAD

**Issue by Mr-Anonymous** [vimeo/vimeo.php#162]
I installed this in my Laravel 5.3 application on php 7.0.* 1 month ago. All working well, however, occasionally I see this error in my laravel log:

```
[2018-03-15 23:50:13] production.ERROR: ErrorException: Undefined index: Range in /home/application/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php:532
Stack trace:
#0 /home/application/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(532): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined index...', '/home/application...', 532, Array)
#1 /home/application/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(282): Vimeo\Vimeo->perform_upload('/home/application...', Array)
#2 /home/application/vendor/graham-campbell/manager/src/AbstractManager.php(236): Vimeo\Vimeo->upload('/home/application...')
#3 /home/application/bootstrap/cache/compiled.php(6468): GrahamCampbell\Manager\AbstractManager->__call('upload', Array)
#4 /home/application/app/Jobs/VimeoUploadJob.php(58): Illuminate\Support\Facades\Facade::__callStatic('upload', Array)
#5 [internal function]: App\Jobs\VimeoUploadJob->handle()
.........
```

The line 58 of the Upload Job uploads the file like this (using Laravel's Vimeo Wrapper):

```
$uri = Vimeo::upload($filePath);
```

Can someone point me what this error message means?

**Comment by erunion** [comment]
That occasionally happens when there's problems uploading your video.

We've overhauled the uploading process in the SDK to reduce, and hopefully eliminate, these kinds of errors. 

Since you're on Laravel 5.3, you should be able to just upgrade to `^2.0` of `vimeo/vimeo-api`. if you're up for upgrading to Laravel 5.5, you can install `^5.0` of `vimeo/laravel`.

**Comment by Mr-Anonymous** [comment]
Thank you for that @erunion 

These errors happen only occasionally and I noticed I haven't seen this log entry the past 2 days. I may be upgrading to Laravel 5.6 soon. If not, I will just upgrade to `^2.0` of `vimeo/vimeo-api` like you suggested.

Thank you for getting back to me.

**Comment by erunion** [comment]
Sounds good!
