### ISSUE TITLE
How can i check that trans code is complete

### ISSUE THREAD

**Issue by yasirrose** [vimeo/vimeo.php#165]
Hi, 

Can you please let me know that how can i check that transcode is complete.

Or can i change the message when video is trans coding? Msg: "This video will be available for viewing shortly."

**Comment by erunion** [comment]
Hi @yasirrose, you can check your transcode status by querying the API for your video `/videos/1234`, and looking at `transcode.status`. If it's `complete`, your video has been transcoded.

**Comment by yasirrose** [comment]
@erunion Thank you. Can i change the default message when video is trans coding? Msg: "This video will be available for viewing shortly."

**Comment by erunion** [comment]
@yasirrose Yep, you can tell the user whatever you'd like.
