### ISSUE TITLE
Upload loop

### ISSUE THREAD

**Issue by icyz** [vimeo/vimeo.php#167]
I want to upload a public video, but I don't know why it's not works.

My (testing) app is registered and approved by vimeo:
<img width="689" alt="schermata 2018-05-01 alle 00 24 17" src="https://user-images.githubusercontent.com/1923633/39453411-21e0ba86-4cd6-11e8-8537-2474b36fb2c9.png">

I've tried this code: 
```
<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

require("vendor/autoload.php");

$client_id = "12345678123456789************";
$client_secret = "ABCDEFG***********************************************";
$token = "345****************************123"; //(token with all scopes)

$lib = new \Vimeo\Vimeo($client_id, $client_secret);
$lib->setToken($token);

$response = $lib->upload('1.mp4'); 

var_dump($response);

```

I get no error, the page still loading (endless).
In my vimeo account I've the new video (but empty)  
<img width="264" alt="schermata 2018-05-01 alle 00 20 02" src="https://user-images.githubusercontent.com/1923633/39453251-7b9fe110-4cd5-11e8-80af-71dd1a1f6252.png">
 
Any ideas?

**Comment by erunion** [comment]
Hey @icyz, can you send our support team the video URL that you received back from the SDK so we can see what happened with the video?

https://vimeo.com/help/contact#tech-api

**Comment by icyz** [comment]
@erunion Thanks for your reply, this is the video URL uploaded by SDK
https://vimeo.com/267321788

(Shall I open a ticket or we can talk here?)
Anyway, thanks you again.

**Comment by erunion** [comment]
@icyz Yeah please do open up a ticket. Sorry!

**Comment by icyz** [comment]
@erunion Done! No problem, thanks for your support!

**Comment by tommypenner** [comment]
@icyz Hi, I'm on the Vimeo Community team providing API support - can you provide your support ticket number? I can then look up your ticket and help you out quicker. Thanks!

**Comment by icyz** [comment]
@tommypenner Sure, this is the vimeo ticket number: 3620085. Thanks

**Comment by jfrei** [comment]
I also had the same issue. The upload() call never finished, and it took me forever to track down the issue. After doing some old print_r() debugs of the response within the perform_upload_tus() function, I found that there were slightly improper array indexes being used.

Vimeo's response had a different case for "Upload-Offset' than what the code was using. Ie. Vimeo would respond with a structure like:

`array(
    'headers' => array(
        'upload-offset' => XXXXX
    ), ...
)`

however the perform_tus_upload() expects 'Upload-Offset'. As such, on our server running PHP 5.6, it continually looped without ever finishing because it couldn't properly access the correct header vars in the response body.

The corrected code below is just a simple replace:

`private function perform_upload_tus($file_path, $file_size, $attempt)
    {
        $url = $attempt['body']['upload']['upload_link'];

        // We need a handle on the input file since we may have to send segments multiple times.
        $file = fopen($file_path, 'r');

        $curl_opts = array(
            CURLOPT_POST => true,
            CURLOPT_CUSTOMREQUEST => 'PATCH',
            CURLOPT_INFILE => $file,
            CURLOPT_INFILESIZE => filesize($file_path),
            CURLOPT_UPLOAD => true,
            CURLOPT_HTTPHEADER => array(
                'Expect: ',
                'Content-Type: application/offset+octet-stream',
                'Tus-Resumable: 1.0.0',
                'upload-offset: {placeholder}',
            )
        );

        // Perform the upload by sending as much to the server as possible and ending when we reach the file size on
        // the server.
        $failures = 0;
        $server_at = 0;
        do {
            // The last HTTP header we set has to be `upload-offset`, since for resumable uploading to work properly,
            // we'll need to alter the content of the header for each upload segment request.
            array_pop($curl_opts[CURLOPT_HTTPHEADER]);
            $curl_opts[CURLOPT_HTTPHEADER][] = 'upload-offset: ' . $server_at;

            fseek($file, $server_at);

            try {
                $response = $this->_request($url, $curl_opts);

                // Successful upload, so reset the failure counter.
                $failures = 0;

                if ($response['status'] === 204) {
                    
                    // If the `upload-offset` returned is equal to the size of the video we want to upload, then we've
                    // fully uploaded the video. If not, continue uploading.
                    if ($response['headers']['upload-offset'] === $file_size) {
                        break;
                    }

                    $server_at = $response['headers']['upload-offset'];
                    continue;
                }

                // If we didn't receive a 204 response from the tus server, then we should verify what's going on before
                // proceeding to upload more pieces.
                $verify_response = $this->request($url, array(), 'HEAD');
                if ($verify_response['status'] !== 200) {
                    $verify_error = !empty($ticket['body']) ? ' [' . $ticket['body'] . ']' : '';
                    throw new VimeoUploadException('Unable to verify upload' . $verify_error);
                }

                if ($verify_response['headers']['upload-offset'] === $file_size) {
                    break;
                }

                $server_at = $verify_response['headers']['upload-offset'];
            } catch (VimeoRequestException $exception) {
                // We likely experienced a timeout, but if we experience three in a row, then we should back off and
                // fail so as to not overwhelm servers that are, probably, down.
                if ($failures >= 3) {
                    throw $exception;
                }

                $failures++;
                sleep(pow(4, $failures)); // sleep 4, 16, 64 seconds (based on failure count)
            } catch (VimeoUploadException $exception) {
                throw $exception;
            }
        } while ($server_at < $file_size);

        return $attempt['body']['uri'];
    }`

**Comment by fizcoder** [comment]
@jfrei thank you! This definitely helped. I managed to get what I needed to work. However the code does not return anything back to the client side. I'm using jQuery Ajax and neither the success or error shows anything.
