### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by dirbey** [vimeo/vimeo.php#172]
I get this when i try to upload video:
> Unable to initiate an upload. [It looks like you've entered some words our spam filters don't like, please try again with different text.]

This is my script:
`$video_data = $vimeo->upload( $videoPath, [
				'name'        => $title,
				'description' => $description,
				'privacy'     => [
					'view' => 'anybody'
				]
			] );`

**Comment by erunion** [comment]
The title and description you're supplying are hitting our spam filters. Use some different text.

**Comment by dirbey** [comment]
OK thank!

**Comment by Srinivasysr2003** [comment]
Hi,
We were using name as "name": "08 Tantrayukti Live Class".  This name is working fine for few uploads and suddenly started failing with below message from last 10 days.  Is this name "Tantrayukti" added to spam list?  We must use this name to upload video to Vimeo and need solution.  If I upload manually with this name, we don't see any issue.  This is happening only with Vimeo API call.  
{'error': "It looks like you've entered some words our spam filters don't like, please try again with different text."}

API Call: '{"upload": {"approach": "pull", "link": "https://?????.zoom.us/rec/webhook_download/WfCRbQXbTqbdzuCfD3T9ijq1qXvJL_0MX.zlaD_xY9G/IvfJYIqXvZgo9u71djBs-tv7WJW-Zs.TVy-tYeHU"}, "name": "Tantrayukti", "description": "", "privacy": {"view": "nobody"}, "privacy.download": false}'
Please provide solution to this problem (Don't ask us to change the name please).
