### ISSUE TITLE
Server reported: Unable to initiate an upload. [Whoops! We are having some technical difficulties, please try again in a minute.]

### ISSUE THREAD

**Issue by sw1tchmx** [vimeo/vimeo.php#174]
$file_name = $_SERVER['DOCUMENT_ROOT']."/".$output_dir.$newfilename;

				#echo 'Uploading: ' . $file_name . "\n";

				try {
				    // Upload the file and include the video title and description.
				    $uri = $lib->upload($file_name, array(
				        'name' => $_FILES["myfile"]["name"],
				        'description' => "This video was uploaded through the Vimeo API's PHP SDK."
				    ));

				    // Get the metadata response from the upload and log out the Vimeo.com url
				    $video_data = $lib->request($uri . '?fields=link');
				    //echo '"' . $file_name . ' has been uploaded to ' . $video_data['body']['link'] . "\n";
				    #$url = "https://vimeo.com/272874411";

**Comment by TaktakTaktouk** [comment]
So, any news! is It just a temporary blocking of your application by vimeo?

**Comment by erunion** [comment]
@TaktakTaktouk @sw1tchmx Sorry for the delay! We've just pushed out a fix for this, can you see if you're still receiving the error?

**Comment by sw1tchmx** [comment]
@erunion No problem! thank you so much! 
it was fixed, works perfect!
