### ISSUE TITLE
Example for: Upload or replace videos from the client?

### ISSUE THREAD

**Issue by Rux77** [vimeo/vimeo.php#177]
Is there an example to: 
**Upload or replace videos from the client**?
https://github.com/vimeo/vimeo.php#upload-or-replace-videos-from-the-client

**Comment by erunion** [comment]
We unfortunately do not have any code examples for uploading or replacing videos from the client. You'll have to follow the instructions we have in our upload guide and build your own integration.

https://developer.vimeo.com/api/upload/videos#form-based
https://developer.vimeo.com/api/upload/videos#replacing-the-source-file-of-a-video
