### ISSUE TITLE
TusCommunicationError when uploading a video of 500MB

### ISSUE THREAD

**Issue by Kinozuko** [vimeo/vimeo.php#190]
Hi, i have an issue when i try to upload videos (500MB as minimum), at begin is uploading correctly, after a while i got an exepcion, it work perfectly when i upload small video (4MB), i'm using python-sdk with the function upload inside my class, in the construct i initialize the user

`class VimeoAPI():

	def upload_file(self,file_path,file_name,file_description):
		file = self._service.upload(file_path,
			data = {
				"name" : file_name,
				"description" : file_description,
				"privacy.add" : False,
				"privacy.comments" : "nobody",
				"privacy.download" : False,
				"privacy.embed" : "private",
				"privacy.views" : "unlisted",
				"chunk_size" : (100 * 1024 * 1024) # 100 MB
			}
		)
		return {
			"response" : True if file else False,	
			"video_uri" : file
		}
`

Python-sdk only use the "tus" option to upload video (when using the upload function inside the Pyvimeo), i'm getting errors based in the tus-py-client, im gettin this exception from tusclient inside exception.py in the vimeo-sdk:

`
 message = getattr(response, 'message')
AttributeError: 'TusCommunicationError' object has no attribute 'message'
`
The exception class is this:

`class TusUploadFailed(TusCommunicationError):
   
 """Should be raised when an attempted upload fails"""
    pass
`

How you can see, the exception is empty and i'm getting that exception, also, i'm getting this:

`
raise TusCommunicationError(error)
tusclient.exceptions.TusCommunicationError: HTTPSConnectionPool(host='files.tus.vimeo.com', port=443): Max retries exceeded with url: /files/vimeo-prod-src-tus-us/8c77eeeb2a0ec1aa466cf045d9c042d6 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1e52422a90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
`
###############################
###############################

`
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='files.tus.vimeo.com', port=443): Max retries exceeded with url: /files/vimeo-prod-src-tus-us/8c77eeeb2a0ec1aa466cf045d9c042d6 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1e52422a90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
`
###############################
###############################

`
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='files.tus.vimeo.com', port=443): Max retries exceeded with url: /files/vimeo-prod-src-tus-us/8c77eeeb2a0ec1aa466cf045d9c042d6 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f1e52422a90>: Failed to establish a new connection: [Errno 110] Connection timed out',))
`
###############################
###############################

`
"Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7f1e52422a90>: Failed to establish a new connection: [Errno 110] Connection timed out
`
###############################
###############################

`
 raise TusUploadFailed(e)
tusclient.exceptions.TusUploadFailed: (55, 'SSL_write() returned SYSCALL, errno = 32')
`
###############################
###############################

`
pycurl.error: (55, 'SSL_write() returned SYSCALL, errno = 32')
`
###############################
###############################

`
raise TusUploadFailed(e)
tusclient.exceptions.TusUploadFailed: (55, 'SSL_write() returned SYSCALL, errno = 32')
`
###############################
###############################

`
raise TusUploadFailed(e)
tusclient.exceptions.TusUploadFailed: (55, 'SSL_write() returned SYSCALL, errno = 32')
`
###############################
###############################

`
self.handle.perform()
pycurl.error: (55, 'SSL_write() returned SYSCALL, errno = 32')
`
 the error is based in the python vimeo-sdk or the tus-py-client  or is something else?

**Comment by erunion** [comment]
@Kinozuko Are you seeing this error in our PHP SDK? Your error output here is for the Python SDK.

**Comment by Kinozuko** [comment]
Yeah, sorry, my bad, i put these issues in the wrong sdk, my bad, this error is from python sdk
