### ISSUE TITLE
Pull approach does not work with spaces in URL

### ISSUE THREAD

**Issue by frutality** [vimeo/vimeo.php#193]
If link contains spaces, file is not uploaded. For example:

"https://example.org/SampleVideo with spaces.mp4" - is fine URL, works in browser

I tried to `rawurlencode` and `urlencode` it, still same result.

Result is error: 

> "field":"upload.link","error_code":2510,"error":"You provided an invalid URL. Please try again."

As workaround, I'll most likely replace all spaces with dashes. But what if there'll be another unsupported symbol? Advices?

**Comment by erunion** [comment]
Unfortunately we don't accept pull URLs with spaces and other potentially unsafe characters in them. You can encode the URL and that should work, however.
