### ISSUE TITLE
upload video while recording?

### ISSUE THREAD

**Issue by yasirrose** [vimeo/vimeo.php#197]
Can i upload the video without providing the size of the file like if i want to upload while recording using resume able upload?

**Comment by erunion** [comment]
Unfortunately, no.

You can do this with our livestreaming APIs by streaming to us as your video is recording and when the stream is over we'll automatically create an archive for you. Unfortunately those APIs are currently private but if you'd like access please contact our community team at https://vimeo.com/help/contact and they'll forward you to someone who can field your request.
