### ISSUE TITLE
Video uploaded through API pull method stuck 'Uploading'

### ISSUE THREAD

**Issue by gdarko** [vimeo/vimeo.php#204]
Hello,

I am trying to integrate vimeo with my WordPress site and when i send video through pull method it's stuck 'Uploading' and doesn't show the video.

The video id is 324339446

[Image example](https://prnt.sc/mygvbq)

Best,
Darko

**Comment by tommypenner** [comment]
Hi Darko, that't not appearing as a pull upload on our end. Can you provide some code snippets or other technical details about how you're attempting your upload?

**Comment by gdarko** [comment]
Yes,

I tried it here. I am actually doing simple plugin for our needs for WordPress.

[Here ](https://github.com/gdarko/wp-vimeo-videos/blob/master/includes/helpers.php#L146) you can see the function that is called to upload the videos via pull.

**Comment by gdarko** [comment]
I actually found the problem and fixed it [here](https://github.com/gdarko/wp-vimeo-videos/commit/8ce324617128569ac22501cb3ba80072259fd76e). I forgot the 'upload' parameter and directly merged those.

Thanks for the swift response.
