### ISSUE TITLE
How to hide the  "uploaded on" date on vimeo

### ISSUE THREAD

**Issue by ken1080** [vimeo/vimeo.php#206]
How can I hide the  "uploaded on" date on vimeo?

**Comment by tommypenner** [comment]
Generally no, video metadata like the uploaded date cannot be hidden; with the API it will always be returned unless you're using the fields filter: https://developer.vimeo.com/api/common-formats#json-filter

Are you talking about the "uploaded on" date shown on-site or elsewhere? Please provide details.

**Comment by ken1080** [comment]
Yes, on the site.  So if I want to send an example of my work (video shooting and editing) videos have a date stamp which I would prefer it not show.

**Comment by tommypenner** [comment]
Understood. Sorry, but the upload date of a video cannot be changed or hidden on vimeo.com.
