### ISSUE TITLE
Update tus-php library to version 1.0.0 or higher

### ISSUE THREAD

**Issue by jbrunemann** [vimeo/vimeo.php#208]
I've tracked a particular dependency conflict down to your use of the `tus-php` library. You use `v0.1.0` but ankitpokhrel has released version `1.0.0` this year. It seems that upgrading the dependency to a stable version of this library would benefit the Vimeo library greatly.

**Comment by yanmorinokamca** [comment]
Same problem here, v.0.1.0 cause a warning for using carbon 1.0. I also got a problem related to kylekatarnls/update-helper.

**Comment by urakozz** [comment]
@jacoboliver @yanmorinokamca 
if you do not use upload functionality, you can try my version (see PR #211 )

adopt your composer.json like this:
```
  "vimeo/vimeo-api": "^3.1.0"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/urakozz/vimeo.php"
    }
  ],
```
