### ISSUE TITLE
Error:  The requested page couldn't be found.  - When I try adding domain in privacy whitelist

### ISSUE THREAD

**Issue by ShinJii89** [vimeo/vimeo.php#213]
Hi,
I have code like this (in PHP using your library):

`$test2 = $lib->request($uri . '/privacy/domains/https://domain.com', 'PUT');`

`$test = $lib->request($uri, array(
        'privacy' => array(
            'view' => 'disable',
            'embed' => 'whitelist',
            'download' => false,
            'comments' => 'nobody',
            'add' => false
        ),
        'embed' => array('logos' => array('vimeo' => false), 'buttons' => array('like' => false, 'share' => false, 'watchlater' => false, 'embed' => false), 'title' => array('owner' => 'hide', 'portrait' => 'hide', 'name' => 'hide'), 'speed' => true),
        'review_page' => array('active' => false)), 'PATCH');`

$test is working but $test2 is showing me that error:

`Array ( [body] => Array ( [error] => The requested page couldn't be found. ) [status] => 404 [headers] => Array ( [Server] => nginx [Content-Type] => application/vnd.vimeo.error+json [Expires] => Thu, 13 Jun 2019 05:23:41 GMT [Cache-Control] => private, no-store, no-cache [Strict-Transport-Security] => max-age=15552000; includeSubDomains; preload [X-Vimeo-DC] => ge [Accept-Ranges] => bytes [Via] => 1.1 varnish [Age] => 0 [Content-Length] => 49 [Date] => Thu, 13 Jun 2019 17:23:41 GMT [Connection] => keep-alive [X-Served-By] => cache-bwi5124-BWI, cache-ams21022-AMS [X-Cache] => MISS, MISS [X-Cache-Hits] => 0, 0 [X-Timer] => S1560446621.282615,VS0,VE105 [Vary] => Accept,Vimeo-Client-Id,Accept-Encoding ) ) `

Why? What am I doing wrong? Why I can't add this stupid domain to whitelist?

Documentation: https://developer.vimeo.com/api/guides/videos/interact#set-off-site-privacy

**Comment by danaburger** [comment]
It looks like you may be using the wrong URL in your request. The full URL for the PUT request is: `/videos/{video_id}/privacy/domains/{domain}`

Does the same error occur when adding`/videos/{video_id}` to your request? (with `{video_id}` being replaced with the id of your video on Vimeo)

**Comment by ShinJii89** [comment]
I know what was wrong - there MUST BE empty array as second parameter
`$lib->request($uri . '/privacy/domains/doman.com', [],'PUT');` - now it's working... I guess somebody should update documentation and examples ;)
