### ISSUE TITLE
I can upload but cannot delete due to url error !

### ISSUE THREAD

**Issue by realtebo** [vimeo/vimeo.php#223]
I use a $client object to upload and to delete videos

```
$client = new Vimeo(
                config('vimeo_client_id'),
                config('vimeo_client_secret'),
                config('vimeo_access_token')
            );
```

I can upload succesfully

 ```
$uri = $client->upload($tmp_storage_path, array(
            "name"          => $file_name,
            "description"   => $file_description,
            "privacy"       => [
                'comments'  => 'nobody',
                'download'  => false,
                'embed'     => 'whitelist',
                'view'      => 'disable',
                'add'       => false,
            ],
        ));
```

But when I try to delete 

`$response = $client->request($uri, [], 'DELETE');
`
I got his absurd error

>  Unable to complete request. [Could not resolve host: api.vimeo.comhttps]

Yes you read right: `api.vimeo.comhttps` ! It's not a copy/paste error. But the same $client has been used to send the video.. why cannnot delete ? 

How it's possible that the url is malformed? We can't alter it in the code!

I'm using

`"vimeo/vimeo-api": "^3.0.2"`
For precision in the lock file I see
```

"name": "vimeo/vimeo-api",
            "version": "3.0.2",
            "source": {
                "type": "git",
                "url": "https://github.com/vimeo/vimeo.php.git",
                "reference": "7013418ff6f2b70003d7025a29ead2c8a7704a80"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/vimeo/vimeo.php/zipball/7013418ff6f2b70003d7025a29ead2c8a7704a80",
                "reference": "7013418ff6f2b70003d7025a29ead2c8a7704a80",
                "shasum": ""
            },

```

A side note: Googling about this error I found this page (I do not know who they are)

https://media.upct.es/videos/?vim=MTk2NA==

Reporting this error in plain text, visible to all

`Fatal error: Uncaught exception 'Vimeo\Exceptions\VimeoRequestException' with message 'Unable to complete request.[Could not resolve host: api.vimeo.comhttps]' in D:\home\site\wwwroot\php\vimeo\src\Vimeo\Vimeo.php:154 Stack trace: #0 D:\home\site\wwwroot\php\vimeo\src\Vimeo\Vimeo.php(127): Vimeo\Vimeo->_request('https://api.vim...', Array) #1 D:\home\site\wwwroot\php\funciones.php(79): Vimeo\Vimeo->request('https://media.u...', Array, 'GET') #2 D:\home\site\wwwroot\php\funciones.php(626): getUrlExtFromVimeo('https://media.u...', '1964', Object(Database)) #3 D:\home\site\wwwroot\videos\index.php(51): getVideo('MTk2NA==') #4 {main} thrown in D:\home\site\wwwroot\php\vimeo\src\Vimeo\Vimeo.php on line 154`

Probably something is going wrong at library side? Or at vimeo server's side?! 

Help, our app is in production ....

**Comment by realtebo** [comment]
I succesfully traced the error to an error **of mine**

This is the incriminated snippet [actually on github here](https://github.com/vimeo/vimeo.php/blob/master/src/Vimeo/Vimeo.php#L124-L138)

```

            case 'DELETE':
                if ($json_body && !empty($params)) {
                    $headers['Content-Type'] = 'application/json';
                    $body = json_encode($params);
                } else {
                    $body = http_build_query($params, '', '&');
                }
                $curl_url = self::ROOT_ENDPOINT . $url;
                $curl_opts = array(
                    CURLOPT_POST => true,
                    CURLOPT_CUSTOMREQUEST => $method,
                    CURLOPT_POSTFIELDS => $body
                );
                break;
```

Dumping the `$curl_url` I see

    https://api.vimeo.comhttps://vimeo.com/12345678

Is is obviously wrong. 

From [official api doc about DELETE](https://developer.vimeo.com/api/reference/videos#delete_video)

> REQUEST
>
> DELETE https://api.vimeo.com/videos/{video_id}

So error **is entirely mine** 

Wrong
-

```
$uri="https://vimeo.com/12345678";
$response = $client->request($uri, [], 'DELETE');
```

Right
-

```
$uri="videos/12345678";
$response = $client->request($uri, [], 'DELETE');
```


> _Sorry, Vimeo staff, it was **my** fault, not yours._

**Comment by marcofloriano** [comment]
$uri="videos/12345678";

shoud be 

$uri="/videos/12345678";

without the initial slash won't work for mr
