### ISSUE TITLE
Add video to showcase

### ISSUE THREAD

**Issue by TaktakTaktouk** [vimeo/vimeo.php#225]
How can I add an uploaded video to a specific showcase, or how can I directly upload the video to showcase.
I did not find any information about showcases in the official documentation.

**Comment by tommypenner** [comment]
@TaktakTaktouk Take a look at the documentation here: https://developer.vimeo.com/api/reference/showcases#add_video_to_album

To add a video to a showcase, make this request: 
```
PUT https://api.vimeo.com/users/{user_id}/albums/{album_id}/videos/{video_id}
```
