### ISSUE TITLE
Vimeo Upload Error - VimeoRequestException: Connection timed out after 30001 milliseconds 

### ISSUE THREAD

**Issue by Mr-Anonymous** [vimeo/vimeo.php#227]
The vimeo uploads has been working for over a year so far without a problem and there has been no changes to the server php or sql or any other settings. However, the past 3 days, some of the slighly large video uploads are failing and I get the following error in the laravel log:

```
[2019-10-14 04:22:38] production.ERROR: Vimeo\Exceptions\VimeoRequestException: Unable to complete request.[Connection timed out after 30001 milliseconds] in /home/myapp/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php:449
Stack trace:
#0 /home/myapp/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(529): Vimeo\Vimeo->_request('https://1512435...', Array)
#1 /home/myapp/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(282): Vimeo\Vimeo->perform_upload('/home/myapp...', Array)
#2 /home/myapp/vendor/graham-campbell/manager/src/AbstractManager.php(236): Vimeo\Vimeo->upload('/home/myapp...')
#3 /home/myapp/bootstrap/cache/compiled.php(6468): GrahamCampbell\Manager\AbstractManager->__call('upload', Array)
#4 /home/myapp/app/Jobs/VimeoUploadJob.php(58): Illuminate\Support\Facades\Facade::__callStatic('upload', Array)
#5 [internal function]: App\Jobs\VimeoUploadJob->handle()
#6 /home/myapp/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#7 /home/myapp/bootstrap/cache/compiled.php(9961): Illuminate\Container\Container->call(Array)
#8 /home/myapp/bootstrap/cache/compiled.php(10076): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(App\Jobs\VimeoUploadJob))
#9 /home/myapp/bootstrap/cache/compiled.php(10054): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(App\Jobs\VimeoUploadJob))
#10 /home/myapp/bootstrap/cache/compiled.php(9964): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#11 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(47): Illuminate\Bus\Dispatcher->dispatchNow(Object(App\Jobs\VimeoUploadJob), false)
#12 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(73): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\BeanstalkdJob), Array)
#13 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(203): Illuminate\Queue\Jobs\Job->fire()
#14 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(153): Illuminate\Queue\Worker->process('beanstalkd', Object(Illuminate\Queue\Jobs\BeanstalkdJob), Object(Illuminate\Queue\WorkerOptions))
#15 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(75): Illuminate\Queue\Worker->runNextJob('beanstalkd', 'high,default,pd...', Object(Illuminate\Queue\WorkerOptions))
#16 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Worker->daemon('beanstalkd', 'high,default,pd...', Object(Illuminate\Queue\WorkerOptions))
#17 /home/myapp/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(84): Illuminate\Queue\Console\WorkCommand->runWorker('beanstalkd', 'high,default,pd...')
#18 [internal function]: Illuminate\Queue\Console\WorkCommand->fire()
#19 /home/myapp/bootstrap/cache/compiled.php(1375): call_user_func_array(Array, Array)
#20 /home/myapp/vendor/laravel/framework/src/Illuminate/Console/Command.php(169): Illuminate\Container\Container->call(Array)
#21 /home/myapp/vendor/symfony/console/Command/Command.php(261): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /home/myapp/vendor/laravel/framework/src/Illuminate/Console/Command.php(155): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /home/myapp/vendor/symfony/console/Application.php(817): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /home/myapp/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Queue\Console\WorkCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /home/myapp/vendor/symfony/console/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /home/myapp/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(121): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /home/myapp/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 {main}  
```

What may be the reason here please? I am receiving numerous logs with the Connection timed out after 30001 milliseconds error message everyday and have no idea what is causing this. It doesn't happen to all videos and it happens to some videos that are longer the 25 seconds in duration it seems. Is this issue from the Vimeo server side or is there something in my server that needs to be reviewed? Is there a timeout setting that I can edit anywhere in vimeo.php? Any help will be appreciated.

I use: Laravel 5.3, php 7.1 and use beanstalkd / supervisord to process queue workers that does the uploading from my server to vimeo via API `"vinkla/vimeo": "3.6",`.

**Comment by mlenton** [comment]
Any news on this @Mr-Anonymous ?

**Comment by Mr-Anonymous** [comment]
yeah. I was continuing to have this issue and it appears the timeout is happening when the REQUEST is sent after the video upload is finished. I then contacted Vimeo support directly since I have a pro account. This was on 23rd Oct. They had asked for more details on the issue such as the API uri, headers, body, Client ID, etc. Below is their email with details request. I never had the time to get back to them with the full details and since Oct 25th I noticed this error is no longer happening. I did not do anything in my server and the error automatically stopped occuring although there are many videos uploaded by my users. I then contacted Vimeo yesterday to check if they did any changes in their end and they said they have not. I will continue to monitor it. Its been 5 days and no error has happened and its weird it disappeared automatically after I contactec vimeo support. Maybe something in the backend in vimeo was updated, I dont know, and now the timeout errors are not showing.

If the error happens again, I will send the details to vimeo support and if I have any further updates, I will post it here.

Below is the copy of the email from vimeo on the details they requested to investigate this issue:

>>>
Hi there,

Thanks for reaching out, and I'm so sorry for the trouble!

To help identify the source of the problem, would it be possible to provide us with a link to one of the affected uploads?

Please also provide the client ID of the application you are using, the last four characters of the access token used to authenticate the request, and a link to the Vimeo account authenticated with that token.

Additionally, please provide the exact full request being made to the API (uri, headers, body), and the exact response (errors, messages, or other behavior) returned by the API.

Thanks so much for your patience and assistance!
Sincerely,
>>>
