### ISSUE TITLE
Root CA

### ISSUE THREAD

**Issue by jwebster45206** [vimeo/vimeo.php#229]
On 10/28/2019, we started experiencing a new issue, related to cURL SSL: "SSL certificate problem: unable to get local issuer certificate."  We were able to resolve it by retrieving and pasting the root CA into vimeo-api.pem, following the instructions that were documented in an earlier version of the sdk. 

We're concerned that this change will be overwritten though when PHP Composer updates the library. 

Just checking to see if this issue is isolated to our application, or if the global vimeo-api.pem file might need to be updated.

**Comment by jwebster45206** [comment]
Note: Today the root CA appears to have changed back to DigiCert, which works with no issues. For at least several hours yesterday, the root CA was Fastly.

**Comment by tommypenner** [comment]
@jwebster45206 Closing this out, it was a temporary issue on Vimeo's end.
