### ISSUE TITLE
Upload Video Uncaught Error: Class 'TusPhp\Tus\Client' not found 

### ISSUE THREAD

**Issue by alokwedig** [vimeo/vimeo.php#231]
Hello ,

I have triedto upload video to vimeo i have received that error how i can resolve it.

`<b>Fatal error</b>:  Uncaught Error: Class 'TusPhp\Tus\Client' not found in /var/www/html/hellowerk_webrtc/vimeo_api/src/Vimeo/Vimeo.php:592
Stack trace:
#0 /var/www/html/hellowerk_webrtc/vimeo_api/src/Vimeo/Vimeo.php(338): Vimeo\Vimeo-&gt;perform_upload_tus('/var/www/html/h...', 670654, Array)
#1 /var/www/html/hellowerk_webrtc/save_vimeo.php(33): Vimeo\Vimeo-&gt;upload('/var/www/html/h...')
#2 {main}
  thrown in <b>/var/www/html/hellowerk_webrtc/vimeo_api/src/Vimeo/Vimeo.php</b> on line <b>592</b><br />`

**Comment by tommypenner** [comment]
@alokwedig Are you still encountering this error when using the most recent release of the library? (version 3.0.5 at current time)

https://github.com/vimeo/vimeo.php/releases/tag/3.0.5

**Comment by alfaranh9** [comment]
yes still facing same problem
please give me solution

**Comment by dskurth** [comment]
I also have the same problem.  Latest library version 3.0.5 .  Not sure where this TUS resides

**Comment by samanaloto** [comment]
Hi @tommypenner any updates on this, please?

I also experience the same problem.  Latest library version 3.0.5

**Comment by ambiondo** [comment]
Hi, same here and version 3.0.5.

Is there any workaround for this bug?

**Comment by cakesoft-utkarsh** [comment]
Hello Team
We are facing this same issue please suggest a workaround or solution.

**Comment by kushaldubal** [comment]
Even I am facing same issue. Did anyone manage to solve this? Seems Vimeo team is not answering

**Comment by dskurth** [comment]
They eventually answer but give you a link to a site that I had already read and tried. Then they disappear when you indicate that you saw it and here is the problem.  I gave up and went to another solution.  I drop the videos into a google drive and vimeo then allows up to upload from there.

**Comment by kushaldubal** [comment]
I managed to get it work. Follow this

1. Update composer by "Composer Update" command, this will download and set up the vendor with all necessary library along with tusphp. 
2. Now go to the root of your project you will find autoload.php link it to vendor folder's autoload.php by "require 'vendor/autoload.php';"

Now try reloading the project it would work. 

Thanks

**Comment by kaushikmakholiyanls** [comment]
> I managed to get it work. Follow this
> 
> 1. Update composer by "Composer Update" command, this will download and set up the vendor with all necessary library along with tusphp.
> 2. Now go to the root of your project you will find autoload.php link it to vendor folder's autoload.php by "require 'vendor/autoload.php';"
> 
> Now try reloading the project it would work.
> 
> Thanks
> Kushal
> [www.smarts3.in](http://www.smarts3.in)

its working thanks

**Comment by tommypenner** [comment]
👋🏽
