### ISSUE TITLE
Vimeo download link giving 403 error

### ISSUE THREAD

**Issue by rana01645** [vimeo/vimeo.php#233]
Hi, I'm using Vimeo on my application. When I'm using API to get a video download link its working fine and giving all videos with the download links.

But when I try to download any video from that provided link its giving error 403 on my webserver.

For instance
wget "https://player.vimeo.com/play/_____"
This wget request giving error like below

--2019-11-05 04:58:57--  https://player.vimeo.com/play/____
Resolving player.vimeo.com (player.vimeo.com)... --IP--
Connecting to player.vimeo.com (player.vimeo.com)|--IP--|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://vimeo.com [following]
--2019-11-05 04:58:57--  https://vimeo.com/
Resolving vimeo.com (vimeo.com)... --IP--,--IP--,--IP--, ...
Connecting to vimeo.com (vimeo.com)--IP--:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2019-11-05 04:58:57 ERROR 403: Forbidden.

**Comment by tommypenner** [comment]
@rana01645 You may be running into an IP address ban on your server or on your webhost. I recommend reaching out to https://vimeo.com/help/contact with your server's IP address, the full URL you're attempting to `wget`, and the full response (headers and body) returned from Vimeo's servers. With that information, support can determine the cause of the 403 error.

**Comment by tommypenner** [comment]
Closing for now as troubleshooting requires sharing private information (Vimeo URL, IP addresses) with Staff.
