### ISSUE TITLE
Latest version 3.0.4 is broken

### ISSUE THREAD

**Issue by AsdYo** [vimeo/vimeo.php#239]
Currently, as I mentioned in this thread #237, the v3.0.4 package is broken, throwing
`   In Vimeo.php line 596:  Attempted to call an undefined method named "setUrl" of class "TusPhp\Tus\Client".`
I understand that manually adding the setter to the other class fixes the issue, but this is not how it should be done and with the next package update it will probably get reverted again...

**Comment by samundra** [comment]
@AsdYo With due respect, I wonder how `setUrl` got into `TusPhp\Tus\Client` in first place. Was it added manually? 🤔

**Comment by AsdYo** [comment]
@samundra Well... Judging also by the other comments there, I guess manually, yes... It's not in the versioned files :)

**Comment by simpleeducation** [comment]
This is completely wrong. 
Please fix it guys, everthing are going to be broken at the deployment moment.

**Comment by AsdYo** [comment]
Thanks for the 3.0.5 fix :)

**Comment by marcuus** [comment]
I have just upgraded to 3.0.5 but the install gives me this:

> In Client.php line 60:
> 
>   Argument 1 passed to TusPhp\Tus\Client::__construct() must be of the type s
>   tring, object given, called in /var/www/vhosts/handover.co.nz/httpdocs/vend
>   or/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on li
>   ne 208
