### ISSUE TITLE
Trouble installing pyvimeo python package

### ISSUE THREAD

**Issue by dbreckenridgejr** [vimeo/vimeo.php#245]
When I try to install pyvimeo I am getting the following error:

(MBN2) z:\PythonCode\MBN>pip install pyvimeo
Collecting pyvimeo
  Using cached PyVimeo-1.0.11.tar.gz (6.9 kB)
Requirement already satisfied: requests>=2.4.0 in c:\programdata\anaconda3\envs\
mbn2\lib\site-packages (from pyvimeo) (2.22.0)
Collecting tuspy==0.2.1
  Using cached tuspy-0.2.1.tar.gz (9.7 kB)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\programdata\anaconda3
\envs\mbn2\lib\site-packages (from requests>=2.4.0->pyvimeo) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\programdata\anaconda3\envs\m
bn2\lib\site-packages (from requests>=2.4.0->pyvimeo) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\pro
gramdata\anaconda3\envs\mbn2\lib\site-packages (from requests>=2.4.0->pyvimeo) (
1.25.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\en
vs\mbn2\lib\site-packages (from requests>=2.4.0->pyvimeo) (2019.11.28)
Collecting pycurl==7.43.0
  Using cached pycurl-7.43.0.tar.gz (182 kB)
    ERROR: Command errored out with exit status 10:
     command: 'C:\ProgramData\Anaconda3\envs\MBN2\python.exe' -c 'import sys, se
tuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\DONALD~1\\AppData\\Local\\Temp
\\pip-install-hnr9qxqd\\pycurl\\setup.py'"'"'; __file__='"'"'C:\\Users\\DONALD~1
\\AppData\\Local\\Temp\\pip-install-hnr9qxqd\\pycurl\\setup.py'"'"';f=getattr(to
kenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"
'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --
egg-base 'C:\Users\DONALD~1\AppData\Local\Temp\pip-install-hnr9qxqd\pycurl\pip-e
gg-info'
         cwd: C:\Users\DONALD~1\AppData\Local\Temp\pip-install-hnr9qxqd\pycurl\
    Complete output (1 lines):
    Please specify --curl-dir=/path/to/built/libcurl
    ----------------------------------------
ERROR: Command errored out with exit status 10: python setup.py egg_info Check t
he logs for full command output.

I wanted to see if you have any suggestions for solving the problem.  Thank you!

**Comment by tommypenner** [comment]
Sorry to hear you're having trouble! Can you file this issue in the appropriate repo? This repo is for the PHP library. The Vimeo Python library is found here: https://github.com/vimeo/vimeo.py/issues
