### ISSUE TITLE
Message: Unable to locate file to upload. 

### ISSUE THREAD

**Issue by NomanMustafa** [vimeo/vimeo.php#257]
i send upload access after 2 days the the access are accept for vimeo upload and Authenticated token with accept upload option 

, but when i using vimeo api the vimeo exceptions here
 Type: Vimeo\Exceptions\VimeoUploadException
Message: Unable to locate file to upload.
my upload path correctly i checked again and again, what is the problem in vimeo api  
my code are 

![Screenshot (5)](https://user-images.githubusercontent.com/50553106/79761752-4e687880-833b-11ea-9fb1-1a8917113d67.png)

![Screenshot (3)](https://user-images.githubusercontent.com/50553106/79761363-c1252400-833a-11ea-9272-5583dc0565c9.png)

**Comment by NomanMustafa** [comment]
> i send upload access after 2 days the the access are accept for vimeo upload and Authenticated token with accept upload option
> 
> , but when i using vimeo api the vimeo exceptions here
> Type: Vimeo\Exceptions\VimeoUploadException
> Message: Unable to locate file to upload.
> my upload path correctly i checked again and again, what is the problem in vimeo api
> my code are
> 
> ![Screenshot (5)](https://user-images.githubusercontent.com/50553106/79761752-4e687880-833b-11ea-9fb1-1a8917113d67.png)
> 
> ![Screenshot (3)](https://user-images.githubusercontent.com/50553106/79761363-c1252400-833a-11ea-9272-5583dc0565c9.png)

**Comment by NomanMustafa** [comment]
Hi please help me for this situation what i do

**Comment by nate-thomas** [comment]
Hey Noman,
I would look into the differences between single and double quotes in PHP (" vs '). It looks like you're accidentally adding escape characters to your path. You can convert the includes string to either a single quote or escape those characters (\t, \xa, etc.)

**Comment by NomanMustafa** [comment]
Thanks Nate-thomas ,
i use single quotes just solve the little problem but the error occurs. 
it doesn't work?

Type: Vimeo\Exceptions\VimeoRequestException
Message: Unable to complete request. [Could not resolve host: api.vimeo.com]

**Comment by NomanMustafa** [comment]
thank you Nate-thomas ,
its working

**Comment by GoodnessEzeokafor** [comment]
can you pass a amzon file data location to vimeo upload api?
