### ISSUE TITLE
Get all the folders that belong to the user

### ISSUE THREAD

**Issue by rodsmr** [vimeo/vimeo.php#278]
Hi, how can I implement [get alle the folders](https://developer.vimeo.com/api/reference/folders#get_projects) ?

**Comment by rodsmr** [comment]
I resolver in this way
`->request("/me/projects", ["direction" => "desc", "sort" => "date"]);`

Is it correct?

**Comment by fjahn** [comment]
Well, does it work? [Here is the documentation](https://developer.vimeo.com/api/reference/folders?version=3.4#get_projects) to do exactly this, and your URI matches the URI in the documentation.

**Comment by rodsmr** [comment]
Yes, it's work!
