### ISSUE TITLE
Peer's Certificate issuer is not recognized

### ISSUE THREAD

**Issue by joshwillcock** [vimeo/vimeo.php#287]
Vimeo/Vimeo.php on line 479

When using uploadTexttrack Vimeo is having a fatal error:
Fatal error: Uncaught Vimeo\Exceptions\VimeoUploadException: Peer's Certificate issuer is not recognized
This happens in Production, Development & local environments, Ubuntu, Centos & Mac.
Video uploads still work so this issue appears to be localised to only the caption part of the API.

I do not believe this to be a code issue but more likely a Vimeo infrastructure issue.

Unfortunately Vimeo support are not willing to provide any assistance, I believe they do not understand what a PHP library is and think that we have custom code fighting with the API.

Dumping out the information on Vimeo's Curl around line 479 we can see the request goes to https://captions.cloud.vimeo.com/captions/xxxxxxxx?expires=xxxxxxxxx&sig=xxxxxxx

This issue only began after a certificate change at the above mentioned address.

Thanks,

Josh

**Comment by aaronm67** [comment]
@joshwillcock Could you update to version 3.0.7 and see if you're still having this issue?

**Comment by joshwillcock** [comment]
Hey Aaron,

Can confirm this fix has resolved the issue. Spent many support tickets being pushed back being told it was our side, think in future I'll always raise here first.

Thank-you for your swift resolution.
