### ISSUE TITLE
How to set destination folder?

### ISSUE THREAD

**Issue by dajeinc** [vimeo/vimeo.php#289]
I can not find anywhere in the documentation how to set the destination folder. I am using a PULL request and all videos go into the general "Videos" folder. I want to upload to a specific folder. How do I do that?

**Comment by fjahn** [comment]
You need to first upload the video and then move it to the folder you want. The way to do the latter is described in [the docs here](https://developer.vimeo.com/api/reference/folders?version=3.4#add_video_to_project).

**Comment by aaronm67** [comment]
The upload video endpoint has a `folder_uri` parameter you can use to set a destination on upload.

https://developer.vimeo.com/api/reference/videos#upload_video
