### ISSUE TITLE
Custom cache location

### ISSUE THREAD

**Issue by sergeolkhovik** [vimeo/vimeo.php#306]
Looks like this library uses TusPhp code (ankitpokhrel/tus-php) to upload videos?
I just upgraded from 2.0.5 to recent 3.x version and now get such messages:
```
PHP Warning:  file_put_contents(xxxx/vendor/ankitpokhrel/tus-php/.cache/tus_php.client.cache): Failed to open stream: Permission denied in xxxx/vendor/ankitpokhrel/tus-php/src/Cache/FileStore.php on line 191
```
I had to set this .cache folder writable for web server but personally I'd like to save all the caches in some other location. So Is it possible to configure Vimeo code with custom caches location (or even engine like redis that is supported by TusPhp)?

**Comment by aaronm67** [comment]
We're updating this library to allow a custom TusClient to be used, rather than forcing the [Vimeo Tus Client](https://github.com/vimeo/vimeo.php/blob/master/src/Vimeo/Upload/TusClient.php).

Look for a release sometime this week.

**Comment by sergeolkhovik** [comment]
Gentlemen, thanks for the update! I just tested it and found one small issue, here's my code:
```
class VimeoCache extends \Vimeo\Upload\TusClientFactory {
    public function getTusClient(string $base_uri, string $url): \TusPhp\Tus\Client
    {
        $client = new \Vimeo\Upload\TusClient($base_uri);
        $client->setUrl($url);
        $path = Path::Cache('vimeo');
        if (!is_dir($path)) {
            Path::mkdir($path);
        }
        $client->setCache(new \TusPhp\Cache\FileStore("$path"));
        return $client;
    }
}
```
based on your sample. It works and uploads but in my case it creates cache file not inside 'path/cache/vimeo' folder, but near with the name: vimeotus_php.client.cache:

![image](https://user-images.githubusercontent.com/5941860/152503543-ad9a921e-c0f2-494f-9864-831e1ea3a6c9.png)

If I change the line to:
```
        $client->setCache(new \TusPhp\Cache\FileStore("$path/"));
```
only in this case I get the file saved inside 'cache/vimeo' folder:

![image](https://user-images.githubusercontent.com/5941860/152503737-ce5e43f5-3450-464e-b989-3b8266f943bc.png)

**Comment by aaronm67** [comment]
Thanks for the feedback!

I'll update the example to be more clear.
