### ISSUE TITLE
It looks like it is not working with PHP 7.4 any more

### ISSUE THREAD

**Issue by plattenbrand** [vimeo/vimeo.php#307]
some sub packages require at least PHP 8.0.2
My hoster does not even offer that version yet.
I am installing it via composer

**Comment by aaronm67** [comment]
What packages are you seeing require PHP 8.0.2?

**Comment by aaronm67** [comment]
This library doesn't depend on most of these packages, you're seeing a PHP 8 dependency from elsewhere.

**Comment by plattenbrand** [comment]
Here is what happens once I require Vimeo/vimeo-api via composer

% composer require vimeo/vimeo-api                   
Using version ^3.0 for vimeo/vimeo-api
./composer.json has been updated
Running composer update vimeo/vimeo-api
Loading composer repositories with package information                                                                                                                                            Updating dependencies                                 
Lock file operations: 31 installs, 0 updates, 0 removals
  - Locking ankitpokhrel/tus-php (v2.2.0)
  - Locking brick/math (0.9.3)
  - Locking guzzlehttp/guzzle (7.4.1)
  - Locking guzzlehttp/promises (1.5.1)
  - Locking guzzlehttp/psr7 (2.1.0)
  - Locking nesbot/carbon (2.56.0)
  - Locking predis/predis (v1.1.10)
  - Locking psr/container (2.0.2)
  - Locking psr/event-dispatcher (1.0.0)
  - Locking psr/http-client (1.0.1)
  - Locking psr/http-factory (1.0.1)
  - Locking psr/http-message (1.0.1)
  - Locking ralouphie/getallheaders (3.0.3)
  - Locking ramsey/collection (1.2.2)
  - Locking ramsey/uuid (4.2.3)
  - Locking symfony/console (v6.0.3)
  - Locking symfony/deprecation-contracts (v3.0.0)
  - Locking symfony/event-dispatcher (v6.0.3)
  - Locking symfony/event-dispatcher-contracts (v3.0.0)
  - Locking symfony/http-foundation (v6.0.3)
  - Locking symfony/mime (v6.0.3)
  - Locking symfony/polyfill-intl-grapheme (v1.24.0)
  - Locking symfony/polyfill-intl-idn (v1.24.0)
  - Locking symfony/polyfill-intl-normalizer (v1.24.0)
  - Locking symfony/polyfill-php72 (v1.24.0)
  - Locking symfony/polyfill-php81 (v1.24.0)
  - Locking symfony/service-contracts (v3.0.0)
  - Locking symfony/string (v6.0.3)
  - Locking symfony/translation (v6.0.3)
  - Locking symfony/translation-contracts (v3.0.0)
  - Locking vimeo/vimeo-api (3.0.8)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 31 installs, 0 updates, 0 removals
  - Installing symfony/deprecation-contracts (v3.0.0): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/http-client (1.0.1): Extracting archive
  - Installing ralouphie/getallheaders (3.0.3): Extracting archive
  - Installing psr/http-factory (1.0.1): Extracting archive
  - Installing guzzlehttp/psr7 (2.1.0): Extracting archive
  - Installing guzzlehttp/promises (1.5.1): Extracting archive
  - Installing guzzlehttp/guzzle (7.4.1): Extracting archive
  - Installing symfony/translation-contracts (v3.0.0): Extracting archive
  - Installing symfony/translation (v6.0.3): Extracting archive
  - Installing nesbot/carbon (2.56.0): Extracting archive
  - Installing predis/predis (v1.1.10): Extracting archive
  - Installing symfony/polyfill-php81 (v1.24.0): Extracting archive
  - Installing ramsey/collection (1.2.2): Extracting archive
  - Installing brick/math (0.9.3): Extracting archive
  - Installing ramsey/uuid (4.2.3): Extracting archive
  - Installing symfony/polyfill-intl-normalizer (v1.24.0): Extracting archive
  - Installing symfony/polyfill-intl-grapheme (v1.24.0): Extracting archive
  - Installing symfony/string (v6.0.3): Extracting archive
  - Installing psr/container (2.0.2): Extracting archive
  - Installing symfony/service-contracts (v3.0.0): Extracting archive
  - Installing symfony/console (v6.0.3): Extracting archive
  - Installing psr/event-dispatcher (1.0.0): Extracting archive
  - Installing symfony/event-dispatcher-contracts (v3.0.0): Extracting archive
  - Installing symfony/event-dispatcher (v6.0.3): Extracting archive
  - Installing symfony/http-foundation (v6.0.3): Extracting archive
  - Installing symfony/polyfill-php72 (v1.24.0): Extracting archive
  - Installing symfony/polyfill-intl-idn (v1.24.0): Extracting archive
  - Installing symfony/mime (v6.0.3): Extracting archive
  - Installing ankitpokhrel/tus-php (v2.2.0): Extracting archive
  - Installing vimeo/vimeo-api (3.0.8): Extracting archive
14 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating optimized autoload files
39 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

**Comment by plattenbrand** [comment]
so the dependence is triggered by vimeo-api

**Comment by aaronm67** [comment]
Can you run `php -v` - this library supports PHP8, it doesn't require it.

**Comment by plattenbrand** [comment]
vagrant@www:~$ php -v
PHP 7.4.27 (cli) (built: Dec 20 2021 21:28:15) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.27, Copyright (c), by Zend Technologies

**Comment by plattenbrand** [comment]
ok, fixed it. I had a local ver of php 8.1.2 running and the server is on 7.4
That mismatch caused it. Did not think it would have that kind of effect.
Thanks for your help

**Comment by aaronm67** [comment]
Great, glad to help!
