### ISSUE TITLE
Making a HEAD {upload.upload_link} request using your PHP SDK

### ISSUE THREAD

**Issue by fuad-tareq** [vimeo/vimeo.php#323]
Part of [Step 3 of the resumable uploads](https://developer.vimeo.com/api/upload/videos) is the ability to verify an upload by sending a `HEAD` request to `upload.upload_link`. I'm aware that this is usually done on the client-side and I've done so successfully using [tus.js](https://github.com/tus/tus-js-client). However, I've recently come up with another use case for this, wherein I'd want to get the result of `HEAD {upload.upload_link}` on the server-side in PHP.

This is useful to find out server-side in scenarios where the user tries to re-upload the same file that was partially interrupted the first time the user attempted to upload it. So let's say days later, the user attempts to upload the same file, so server-side we'd want to know if the video file was fully uploaded or partially uploaded to Vimeo. And if it's the latter, we'd then get the upload-offset for that video (so as to be able to resume uploading the rest of the file) and offer the user the ability to resume upload where they previously left of.

Where I'm having a problem executing this is that I am unable to execute `HEAD {upload.upload_link}` using your PHP SDK's `$lib->request()` method since anything I put as the `$uri` gets prepended by the "https://api.vimeo.com" root endpoint.

**Comment by aaronm67** [comment]
I think this is probably a case where it makes the most sense to just use curl directly rather than go through the library - this is an edge case that would be a little confusing to use within the library. You can see how the Vimeo library does this with vanilla curl_{x} calls, https://github.com/vimeo/vimeo.php/blob/master/src/Vimeo/Vimeo.php#L541, or there are many different curl wrappers you can use.

**Comment by fuad-tareq** [comment]
Thanks for your quick response @aaronm67. I've actually been trying `curl` all day unsuccessfully. I seem to be missing something possibly simple? I've tried a lot of variations of the following but I keep getting a 412 when trying to `curl` the upload_link.
```
$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_URL => $uploadLink,
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => 'HEAD',
  CURLOPT_POSTFIELDS => array(),
  CURLOPT_AUTOREFERER, true,
  CURLOPT_USERAGENT => 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.17 (KHTML, like Gecko) Chrome/24.0.1312.52 Safari/537.17', // Have tried 'vimeo.php 3.0.8; (http://developer.vimeo.com/api/docs)' here as well which is used in your PHP SDK.
  CURLOPT_FOLLOWLOCATION => true,
  CURLOPT_SSL_VERIFYPEER => false, // Have tried this with true.
  CURLOPT_SSL_VERIFYHOST => false, // Have tried this with 2 as is used in your SDK.
  CURLOPT_HTTPHEADER => array(
     'Tus-Resumable' => '1.0.0',
     'Accept' => 'application/vnd.vimeo.*+json;version=3.4',
     'Authorization' => 'Bearer [token]'
   )
));

$result = json_decode( curl_exec($curl) );
curl_close($curl);
```
I've tried replicating as many `curl` settings from your SDK as I've seen but it's been a merciless guessing game lol. Any hints would be really helpful here.
