### ISSUE TITLE
I like this. Ideally we would use Gson versions (which would map to the API version) in addition to this. Then only invalidate the cache if we know there will be a breaking change. This would also help us a bit with any other persistence (like turnstile).

### ISSUE THREAD

**Issue by zerze1** [vimeo/vimeo.php#328]
I like this. Ideally we would use Gson versions (which would map to the API version) in addition to this. Then only invalidate the cache if we know there will be a breaking change. This would also help us a bit with any other persistence (like turnstile).

https://sites.google.com/site/gson/gson-user-guide#TOC-Versioning-Support
Name changes: https://futurestud.io/tutorials/gson-model-annotations-multiple-deserialization-names-with-serializedname
http://memorynotfound.com/gson-versioning-support/

_Originally posted by @kvenn in https://github.com/vimeo/vimeo-networking-java/issues/252#issuecomment-327844572_

**Comment by aaronm67** [comment]
This is not for this package, it looks like it's for a deprecated android package.
