### ISSUE TITLE
VIMEO AI

### ISSUE THREAD

**Issue by ronlinet** [vimeo/vimeo.php#337]
Any plans to include Vimeo AI to the Vimeo API ? 

![Screenshot 2024-07-21 at 7 10 18 PM](https://github.com/user-attachments/assets/a88ce3b0-4e71-4e16-8ecf-2b20986787c2)

**Comment by aaronm67** [comment]
Please open a feature request at https://vimeo.com/help/contact, or with your account manager, they can potentially help prioritize AI features in the API, we don't accept new feature requests through github.
