### ISSUE TITLE
I can't upload a video through localhost

### ISSUE THREAD

**Issue by mohdqasim98** [vimeo/vimeo.php#47]
1)Can I make such request through localhost (for development purpose) ?If yes , how
2)Do I need ssl certificate on development server to make such requests ?

The exception thrown is "Server reported: Unable to get an upload ticket."

**Comment by Dashron** [comment]
Localhost should work just fine.

Make sure you have been granted upload permissions from Vimeo, and you have followed our troubleshooting guide: https://github.com/vimeo/vimeo.php#troubleshooting.

If you still encounter issues, please post the contents of the `$ticket` variable from here: https://github.com/vimeo/vimeo.php/blob/master/src/Vimeo/Vimeo.php#L349

**Comment by Dashron** [comment]
Hi @mohdqasim98. If you are still running into issues, feel free to re-open this and let us know!

**Comment by yilmazhasan** [comment]
Hi @Dashron, I have been getting this error too when trying to take a upload ticket with redirect_url is localhost, does anything be updated related with this?

**Comment by erunion** [comment]
@yilmazhasan Sorry for the delay on this, we recently put in some security protocol changes to block private IPs from being used as redirect URLs and it may have caught `localhost` up in the mix. Someone on the team will be looking into it later this week or early next.

**Comment by tommypenner** [comment]
Resolved internally (API-495)
