### ISSUE TITLE
Tags with spaces

### ISSUE THREAD

**Issue by kavadas** [vimeo/vimeo.php#48]
Hi,

It looks like there is no way to add a tag with spaces using the library. 

Both:
```php
$newTag = 'Test Tag';
$response = $lib->request('/videos/'.$videoId.'/tags', array('tag' => $newTag), 'PUT');
```
And:
```php
$newTag = 'Test Tag';
$response = $lib->request('/videos/'.$videoId.'/tags/'.$newTag, array(), 'PUT');
```
Do not work. In both cases the video is tagged with the word "Test". 
I am not sure if this is an issue of the library or the API.

**Comment by Dashron** [comment]
Thanks for letting us know. If you urlencode the $newTag it will probably work. We'll look into additional solutions soon!

**Comment by kavadas** [comment]
Thanks for replying. 
Unfortunately urlencode does not solve the issue. I also tried that but i forgot to mention about it when i opened this issue. 
I tried the following code:
```php
$newTag = urlencode('Test Tag');
$response = $lib->request('/videos/'.$videoId.'/tags/'.$newTag, array(), 'PUT');
```
The result was to have the video tagged with the tag "Test+Tag".

I took a look at the source code of the library and i didn't notice any kind of processing regarding the URL of the requests. So i guess that this is probably an API issue and not an issue of the library.

**Comment by Dashron** [comment]
Oh my bad, use rawurlencode instead. urlencode isn't to spec

**Comment by kavadas** [comment]
Adding tags with spaces is working indeed when rawurlencode is used. However, a different issue is raised now. Tags with spaces cannot be deleted using the API.

```php
$existingTag = rawurlencode('Test Tag');
$response = $lib->request('/videos/'.$videoId.'/tags/'.$existingTag, array(), 'DELETE');
```
The response status is 204 however the tag does not get removed.

**Comment by Dashron** [comment]
Cool. We'll look into that asap!

**Comment by Dashron** [comment]
Sorry for the delay, just wrote a server side fix for this and it's going out now. It should be live in the next couple of minutes.
