### ISSUE TITLE
I can not get Video details

### ISSUE THREAD

**Issue by piyushpatil027** [vimeo/vimeo.php#50]
hi,

Hope you are doing great.I am using your pkg for vimeo integration.When i am using 
$result =   Vimeo::request('/me/videos', ['per_page' => 10], 'GET'); )
 this method it is giving 
{"error":"A valid user token must be passed."}
this error.
Can you tell me whats i am doing wrong.

**Comment by vinkla** [comment]
Hi @piyushpatil027, could you maybe share a little bit more how you've integrated the `Vimeo` library in your application?

**Comment by piyushpatil027** [comment]
yes. I have integrated vinkla/vimeo this pkg in my project. First i update my composer and after create config file for vimeo then i wrote client_id, client_secret , access_token.
Access_tokecn which i have generated from app portion.

**Comment by vinkla** [comment]
Which version of the package are you using?

**Comment by piyushpatil027** [comment]
1.0

On Fri, Mar 13, 2015 at 2:31 PM, Vincent Klaiber <notifications@github.com>
wrote:

> Which version of the package are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vimeo/vimeo.php/issues/50#issuecomment-78875939>.
>



-- 
Thanks & Regards
Piyush Patil


Software Engineer
Sky Id : piyushpatil27
Email Id : piyushpatil027@gmail.com
Mobile No : 09096871715

**Comment by vinkla** [comment]
Which version of Laravel are you using?

**Comment by piyushpatil027** [comment]
4.2

On Fri, Mar 13, 2015 at 2:33 PM, Vincent Klaiber <notifications@github.com>
wrote:

> Which version of Laravel are you using?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vimeo/vimeo.php/issues/50#issuecomment-78876491>.
>



-- 
Thanks & Regards
Piyush Patil


Software Engineer
Sky Id : piyushpatil27
Email Id : piyushpatil027@gmail.com
Mobile No : 09096871715

**Comment by vinkla** [comment]
And you have published your configuration file to `app/config/packages`?

**Comment by piyushpatil027** [comment]
yes.

On Fri, Mar 13, 2015 at 2:35 PM, Vincent Klaiber <notifications@github.com>
wrote:

> And you have published your configuration file to app/config/packages?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vimeo/vimeo.php/issues/50#issuecomment-78877691>.
>



-- 
Thanks & Regards
Piyush Patil


Software Engineer
Sky Id : piyushpatil27
Email Id : piyushpatil027@gmail.com
Mobile No : 09096871715

**Comment by vinkla** [comment]
And the service provider is registered?

**Comment by piyushpatil027** [comment]
yes. All setting properly done.

On Fri, Mar 13, 2015 at 2:38 PM, Vincent Klaiber <notifications@github.com>
wrote:

> And the service provider is registered?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vimeo/vimeo.php/issues/50#issuecomment-78878847>.
>



-- 
Thanks & Regards
Piyush Patil


Software Engineer
Sky Id : piyushpatil27
Email Id : piyushpatil027@gmail.com
Mobile No : 09096871715

**Comment by vinkla** [comment]
The facade also then? Maybe you could share the class which handles the `Vimeo` request?

**Comment by piyushpatil027** [comment]
hi Vincent,

Thanks for reply. Actually there was some mistake in my code. I got my
mistake.
Thanks.
Second Issue I can not upload video from localhost.

It is giving below error.

can you help me for uploading video.

exception 'Vimeo\Exceptions\VimeoUploadException' with message 'Unable to
get an upload ticket.' in
/usr/share/nginx/html/cardiomeet/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php:330
Stack trace: #0
/usr/share/nginx/html/cardiomeet/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(292):
Vimeo\Vimeo->perform_upload('foo.avi', Array) #1
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(211):
Vimeo\Vimeo->upload('foo.avi', false) #2
/usr/share/nginx/html/cardiomeet/app/controllers/Testingcontroller.php(25):
Illuminate\Support\Facades\Facade::__callStatic('upload', Array) #3
/usr/share/nginx/html/cardiomeet/app/controllers/Testingcontroller.php(25):
Vinkla\Vimeo\Facades\Vimeo::upload('foo.avi', false) #4 [internal
function]: Testingcontroller->index() #5
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(231):
call_user_func_array(Array, Array) #6
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(93):
Illuminate\Routing\Controller->callAction('index', Array) #7
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(62):
Illuminate\Routing\ControllerDispatcher->call(Object(Testingcontroller),
Object(Illuminate\Routing\Route), 'index') #8
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(967):
Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route),
Object(Illuminate\Http\Request), 'Testingcontroll...', 'index') #9
[internal function]:
Illuminate\Routing\Router->Illuminate\Routing\{closure}() #10
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Routing/Route.php(109):
call_user_func_array(Object(Closure), Array) #11
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1033):
Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #12
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1001):
Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#13
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(775):
Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #14
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(745):
Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#15
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Session/Middleware.php(72):
Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request),
1, true) #16
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Cookie/Queue.php(47):
Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1,
true) #17
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Cookie/Guard.php(51):
Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#18
/usr/share/nginx/html/cardiomeet/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23):
Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#19
/usr/share/nginx/html/cardiomeet/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(641):
Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request)) #20
/usr/share/nginx/html/cardiomeet/public/index.php(49):
Illuminate\Foundation\Application->run() #21 {main}zdfzd







On Fri, Mar 13, 2015 at 2:42 PM, Vincent Klaiber <notifications@github.com>
wrote:

> The facade also then? Maybe you could share the class which handles the
> Vimeo request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vimeo/vimeo.php/issues/50#issuecomment-78880469>.
>



-- 
Thanks & Regards
Piyush Patil


Software Engineer
Sky Id : piyushpatil27
Email Id : piyushpatil027@gmail.com
Mobile No : 09096871715

**Comment by vinkla** [comment]
Have you had a look at https://github.com/vimeo/vimeo.php/issues/47#issuecomment-72739413? There @Dashron gives feedback about this issue.

**Comment by vinkla** [comment]
@piyushpatil027 If you still have problem with the localhost please create a second issue.

@Dashron I think this could be closed.
