### ISSUE TITLE
Uploading video through SSL

### ISSUE THREAD

**Issue by gvhuyssteen** [vimeo/vimeo.php#51]
Trying to upload a video that sits on the web server to Vimeo and I'm getting the following error:

> A valid user token must be passed. Status code: 401

I'm using Laravel 4.2 with
"vinkla/vimeo": "~1.0"  and Vimeo PHP Api version=3.2 (vimeo.php 1.0;)

The config file has the correct keys used to upload.

Uploading from localhost works perfectly.

The recommended fix from this website: http://unitstep.net/blog/2009/05/05/using-curl-in-php-to-access-https-ssltls-protected-sites/  have been implemented but still getting the same error.

Currently my Vimeo.php file have these fixes implemented: https://github.com/dstelljes/vimeo.php/commit/babb5da75a65e56717c55f1f287acbc2583292e0

I'm still getting the same error. "A valid user token must be passed"

Are there any other changes I need to implement to get this working?

**Comment by vinkla** [comment]
Is the access token in the configuration file? They had a similar problem in #50.

**Comment by gvhuyssteen** [comment]
Hi Vinkla,

First of all, thank you for the time to write a Laravel package for Vimeo!

I have tried leaving the access token null as well as entering the access token that I had from vimeo.

Always the same error. "A valid user token must be passed."

**Comment by vinkla** [comment]
Anytime! I needed it myself. Did you look through the other issues? Did they help?

**Comment by gvhuyssteen** [comment]
I have been looking and reading through fixes for 2 days now.
Posting on Github was my last option.

**Comment by vinkla** [comment]
Make sure you have been granted upload permissions from Vimeo, and you have followed our troubleshooting guide: https://github.com/vimeo/vimeo.php#troubleshooting.

If you still encounter issues, please post the contents of the `$ticket` variable from here:https://github.com/vimeo/vimeo.php/blob/master/src/Vimeo/Vimeo.php#L349

**Comment by gvhuyssteen** [comment]
Let me give a bit more detail.

A user uploads a video using a form to my web server. I then use Vimeo::upload to upload the file from a public directory to Vimeo.
```php
$vimeo = Vimeo::upload($directory . '/' . $filename, false);
```
We are using a wildcard SSL certificate (If that matters in any way)

Here is what I get back in $ticket:
```json
{
    "error": {
        "type": "Vimeo\\Exceptions\\VimeoUploadException",
        "message": "{\"body\":{\"error\":\"A valid user token must be passed.\"},\"status\":401,\"headers\":{\"Date\":\"Thu, 19 Mar 2015 12\",\"Server\":\"nginx\",\"Content-Type\":\"application\\\/vnd.vimeo.error+json\",\"Cache-Control\":\"no-cache, max-age=315360000\",\"WWW-Authenticate\":\"Bearer error=\\\"invalid_token\\\"\",\"Expires\":\"Sun, 16 Mar 2025 12\",\"Content-Length\":\"46\",\"Accept-Ranges\":\"bytes\",\"Via\":\"1.1 varnish\",\"X-Served-By\":\"cache-lcy1128-LCY\",\"X-Cache\":\"MISS\",\"X-Cache-Hits\":\"0\",\"X-Timer\":\"S1426767198.877492,VS0,VE87\",\"Vary\":\"Accept,Vimeo-Client-Id,Accept-Encoding\"}}",
        "file": "\/var\/www\/dev\/vendor\/vimeo\/vimeo-api\/src\/Vimeo\/Vimeo.php",
        "line": 345
    }
}

```

**Comment by vinkla** [comment]
@Dashron do you have any input on this?

**Comment by Dashron** [comment]
The access token you use has to be authenticated to a user, so you should be able to successfully request `GET https://api.vimeo.com/me?access_token=XXXX`.

If that url doesn't work, try `GET https://api.vimeo.com/users/dashron?access_token=XXXX`.
If the first url doesn't work, but the second one does you have a client authentication token. These are not associated with users, and you can not upload a video without a user access token.

If the second url doesn't work your token is invalid and you should generate a new one.

If both urls work, and you still can not generate a token your app likely does not have upload permissions for that user. There are many different levels of permission and you might only have access to upload on behalf of the owner of the api application. To verify this you can contact vimeo through vimeo.com/help/contact

**Comment by gvhuyssteen** [comment]
Thank you for your response.
Both urls work and I have selected the upload permission when I created the access token.

I will contact Vimeo support for further investigation.

**Comment by gvhuyssteen** [comment]
Vimeo support is so very slow... Been waiting 4 days for a response now.

**Comment by gvhuyssteen** [comment]
6 days in and no feedback from Vimeo support.  Is there anyone else that can help me?

**Comment by Dashron** [comment]
There have been some issues with Vimeo's support service over the last couple of days. None of the support cases we have received in the last couple of days included the message you provided earlier. Can you submit a new request and ask for it to be assigned immediately to Aaron?

**Comment by gvhuyssteen** [comment]
Thank you for coming back to me, Dashron.
I have resubmitted the query to the API support team.

**Comment by gvhuyssteen** [comment]
After regenerating a token and added all available scopes to the token, I'm getting a different error.

Scopes used:
```text
public private purchased create edit delete interact upload
```

I changed the access key in the config file to the new one I just generated.

This is the response that I am now getting back through an SSL connection.

```json
{
    "error": {
        "type": "Vimeo\\Exceptions\\VimeoUploadException",
        "message": "{\"body\":null,\"status\":0,\"headers\":[]}",
        "file": "/var/www/dev/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php",
        "line": 347
    }
}
```

These are my curl option defaults:

```php
$curl_opt_defaults = array(
            CURLOPT_HEADER => 1,
            CURLOPT_RETURNTRANSFER => true,
            CURLOPT_SSL_VERIFYPEER => true,
            CURLOPT_SSL_VERIFYHOST => 2,
            CURLOPT_TIMEOUT => 30,
            CURLOPT_CAINFO => dirname(__FILE__) . 'ca.crt'
        );
```

Why is this so difficult?

Even though we support Vimeo with a PRO account, Vimeo is not supporting us with sufficient support as we had not received any feedback from Vimeo.

On the verge of moving away from Vimeo to store and stream videos from.

**Comment by gvhuyssteen** [comment]
Moved the whole laravel based website to a brand new server with no SSL installed.

I did a clean vendor install, meaning that this Vimeo package was installed as is with no modifications.

This is the error I'm receiving now.

```json
{
    "error": {
        "type": "Vimeo\\Exceptions\\VimeoUploadException",
        "message": "Unable to get an upload ticket.",
        "file": "/var/www/disturping.com/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php",
        "line": 336
    }
}
```

I tried two different access tokens. Same errors.

Officially confused.

**Comment by Dashron** [comment]
{\"body\":null,\"status\":0,\"headers\":[]} is usually an ssl based issue (status 0 means it never left the servers)

"Unable to get an upload ticket" is a bad error message that we are going to be fixing soon. You can find it here: https://github.com/vimeo/vimeo.php/blob/master/src/Vimeo/Vimeo.php#L350. If you log out the $ticket variable from the condition on the line above you will see a much clearer failure cause.

**Comment by gvhuyssteen** [comment]
Hi Dashron,

When I log the $ticket, I get the same error message as before. (Post #1)

We realised that there was something wrong with our mail server and could not receive the responses from Vimeo support. I have now pushed back to support and hopefully we can sort this issue out.

Apologies for the lashing out earlier. I realise that it was completely my fault for not receiving support emails.

**Comment by Dashron** [comment]
No worries, we have definitely encountered that issue before, and it frustrates us as much as it must frustrate you.

I found your ticket and just replied with some more questions about your access token.

**Comment by gvhuyssteen** [comment]
So after spending a bit more time on the Vimeo php library, I finally solved the issue.

The client_id, client_secret and access_token was not being set once I moved it to the dev server.
Using the same project on local host actually sets the credentials correctly.

Thank you all for your help.

**Comment by Dashron** [comment]
Glad to hear it's fixed. Let us know if you encounter any more issues!
