### ISSUE TITLE
Coding Standards and Naming Conventions

### ISSUE THREAD

**Issue by vinkla** [vimeo/vimeo.php#61]
What about converting the code to follow the [PSR-2 Coding Standard](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md) and [PHP-FIG Naming Conventions](https://github.com/php-fig/fig-standards/blob/master/bylaws/002-psr-naming-conventions.md)? It can be done fast with [PHP Coding Standards Fixer](http://cs.sensiolabs.org/). This is a breaking change but if we are going to bump the version number anytime soon we could throw this in as well. What do you think?

**Comment by Dashron** [comment]
I'm cool with that. We have a new dev starting on the 20th who will jump in and get this ready for a new release (cert pinning, better error messages are the top priorities). With that we can incorporate this standard.

**Comment by vinkla** [comment]
Great! Maybe we could integrate https://styleci.io as well. Its a PHP coding style continuous integration service. It goes through every pull request and commit to check the quality of the code. To see if it follow our guidelines. 

I think we should add CONTRIBUTING.md file as well to let the developers know which rules this package enforces. [Here is an example.](https://github.com/vinkla/vimeo/blob/master/CONTRIBUTING.md)

**Comment by vinkla** [comment]
Since this is breaking we should also release all new updates as version `2.0`.

**Comment by Dashron** [comment]
Definitely on all three.

**Comment by vinkla** [comment]
Super. I've updated the branch-alias in #54 to point to version `2.0`.
