### ISSUE TITLE
Upload function broken

### ISSUE THREAD

**Issue by issander** [vimeo/vimeo.php#71]
It seems to have been broken because [this commit](https://github.com/vimeo/vimeo.php/commit/12578cb8e3374bc795669d41bff365524d80ee9a) removed the following line from the "perform_upload" function:
```
$upload_response = $this->_request($url, $curl_opts);   //  Send what we can.
```
When I manually added this line back in my uploads started working.

**Comment by Dashron** [comment]
Thanks. Unit tests coming next to ensure little regressions like this don't re-surface.
