### ISSUE TITLE
Unable to complete request

### ISSUE THREAD

**Issue by iwright1962** [vimeo/vimeo.php#77]
I am trying to set-up the Vimeo API for PHP and I am receiving the error below. Is there a checklist to confirm required steps and files? Please help!

Fatal error: Uncaught exception 'Vimeo\Exceptions\VimeoRequestException' with message 'Unable to complete request.[Problem with the SSL CA cert (path? access rights?)]' in /home3/iwright/public_html/church/src/Vimeo/Vimeo.php:154 Stack trace: #0 /home3/iwright/public_html/church/src/Vimeo/Vimeo.php(127): Vimeo\Vimeo->_request('https://api.vim...', Array) #1 /home3/iwright/public_html/church/indexVimeo.php(27): Vimeo\Vimeo->request('/me') #2 {main} thrown in /home3/iwright/public_html/church/src/Vimeo/Vimeo.php on line 154

**Comment by Dashron** [comment]
We've ironed out all known issues, so this is a new one for me.

What operating system are you using, and can you tell me what permissions are enabled on the libraries certificates directory, and all files within? (let me know if you need more help with this)

**Comment by iwright1962** [comment]
Hi Aaron,
Thanks for your super-fast reply. Thanks for asking about the certificates; it looks like I did not have the folder structure correct on my site. I don't see the error message anymore. Now the web page displays as shown below. Does it appear that the connection from my web site to Vimeo is working now?
 
Array (    [body] => Array        (            [uri] => /users/40872186            [name] => Ian Wright ...
 
Date: Wed, 10 Jun 2015 09:58:24 -0700

**Comment by Dashron** [comment]
Looks like a standard response for a single user. Glad everything's fixed!

**Comment by iwright1962** [comment]
Hi Aaron,
I have been having a very difficult time trying to integrate Vimeo API into my web site and judging from my Internet research, I am not alone. It seems there is a lack of any documentation that would be considered a User's Guide. The documentation that is provided would be a good example of reference documentation, but I find a lack of complete examples of js or PHP a major barrier to getting functionality to work. I would find it very useful to have a simple, complete working example of how to upload a video using JavaScript so that I can upload directly from browser to Vimeo. The code provided on GitHub for js is not a working example. It seems the documentation provided is more for Vimeo staff than for general use. Normally a service such as Vimeo would provide a simple, quick-start example to get developers up and running quickly. Once some functionality is working, it is much easier to add more functionality. 
 
I am working on a web site for my church and I know they will opt for an upgraded Vimeo service if I can get the Vimeo-to-thier web site integration working. Do you know of a working example of using js to upload videos directly from browser to Vimeo? I have gotten the PHP upload working, but since my Internet Service Provider limits my file size, I must use the direct upload method. I would think this is a common situation that Vimeo could capitalize on if the documentation was more user-friendly. 
 
I hope that you interpret this email as constructive feedback.
 
Date: Wed, 10 Jun 2015 11:21:36 -0700

**Comment by Dashron** [comment]
For client side uploading, specifically simple form post from your browser to the vimeo API, we have a fairly thorough step by step guide here: https://developer.vimeo.com/api/upload#http-post-uploading.

We don't have a great guide for uploading on the client using resumable uploads, because we are holding off until we launch our own client side javascript upload library, and some improved security measures.

We're about a month away from launching some getting started guides, a couple of tutorials, and a significantly restructured reference guide which should help new and old developers alike. If you would like, I can send you a link to some of the alpha documentation. It should be a little easier to follow!

**Comment by iwright1962** [comment]
Thanks for your super-fast response. It sounds like you have already identified the need for simplified documentation that I discussed, and that is great.  I would love to see the alpha documentation of getting started guides and tutorials. Please send what you can since I am eager to get the Vimeo functionality of my church's web site working to demonstrate to my church leaders.
 
Date: Fri, 12 Jun 2015 11:01:05 -0700

**Comment by Dashron** [comment]
Lets take this off of github then. Send us a message through vimeo.com/help/contact and ask for Aaron.

**Comment by iambasitali** [comment]
Dashron I am facing the same issue but I did not found  any solution yet please guide me how can I fix that SSL Connection issue.

**Comment by erunion** [comment]
@iambasitali Send a message to https://vimeo.com/help/contact and we can work with you offline to figure out what problem is.
