### ISSUE TITLE
Update the upload example

### ISSUE THREAD

**Issue by Dashron** [vimeo/vimeo.php#80]
add set name/description

**Comment by chandrateja** [comment]
FIRMWARE UPDATE IN REMOTE SERVER
In that for update firmware so many http request is there along with that i am uploading file on remote server in that header cookies and mime type is also there  
please help me how to upload file to remote server with cookies and mime type

header::


POST /page/file_upload.html?SOURCE=FirmwareImage HTTP/1.1
Host: 192.168.1.202
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Referer: http://192.168.1.202/page/fw_update.html
Cookie: test=1; SessionCookie=xqnppGaeIe4UbANAwNSRtpN4SrbQ7F5o000; SESSION_ID=1; BMC_IP_ADDR=192.168.1.212; Language=EN; Username=dsfbj; PNO=4; Extendedpriv=259; gMultiLAN=true; settings={eth:[0,1],ethstr:['eth0','eth1'],lan:[1,8],enable:[1,1],features:'NWLINK,SYSTEM_FIREWALL,SYSTEM_FIREWALL_TIMEOUT,EXTENDED_PRIV,CIRCULAR_SEL,DISABLE_EMPTY_PASSWORD,IPV6_COMPLIANCE,LANG_SUPPORT,EN,SAVE_SELLOG,SET_SENSOR_THRESHOLDS,JAVASOL,NWBONDING,POWER_CONSUMPTION,SERVICES,SESSION_MANAGEMENT,BMC_RECOVERY,PRESERVECONF,FIRMWARE_FLASH_SUPPORT,SECTIONFLASH,VERSION_CMP_FLASH,FW_IMAGE,BACKUP_CONFIG,NTP_SERVER_SUPPORT,SINGLE_PORT_APP,RUNTIME_SINGLEPORT_SUPPORT,RUNTIME_LICENSE,TSIG,MDNS,TIMEZONE_SUPPORT,UARTLOG,UARTLOG_REMOTE,HPM_SUPPORT,AUTOVDORECORD,AUTOVDORECORD_REMOTE,ADVISER_SUPPORT,KB_LANG_SELECT_SUPPORT,RUNTIME_HOST_LOCK,HOST_LOCK_AUTO,KVM_SESSION_TIMEOUT,KVM_SESSION_RECONNECT,AUTO_RESIZE_KVM_CLIENT_WINDOW,MEDIA_REDIR_READ_WRITE_ONLY,JAVA_CD_IMAGE_REDIR,WEB_PREVIEW,CAPTURE_BSOD_RAW,CAPTURE_BSOD_RAW,MULTIPLE_USER_VMEDIA,VMEDIA_MAX_COUNT_FOR_KVM,IMG_REDIRECTION,LMEDIA,IMG_REDIRECTION,RMEDIA,SD_SERVER_SUPPORT,NCSI_SUPPORT,PAM_REORDERING,AD_SUPPORT,LDAP_SUPPORT,RADIUS_SUPPORT,'}; License=''
Connection: keep-alive
Content-Type: multipart/form-data; boundary=---------------------------1483912179732659506492514283
Content-Length: 33554687
CRLF
MIME Multipart Media Encapsulation, Type: multipart/form-data, Boundary: "---------------------------2003170221614335378910293499"
-----------------------------2003170221614335378910293499
Content-Disposition: form-data; name="image"; filename="COB-N100-PNK-IPMI-V1.0.10052.ima"
Content-Type: application/octet-stream
Media Type: application/octet-stream (33554432 bytes)
-----------------------------2003170221614335378910293499--
