### ISSUE TITLE
Upload using URL

### ISSUE THREAD

**Issue by Geekathon** [vimeo/vimeo.php#82]
Hi , Can i just edit the vimeo lib and change the line no. 314 in Vimeo.php library file from "type:streaming" to "type:pull" and upload it using URL. 

Can i edit that ?

**Comment by Dashron** [comment]
The upload function isn't useful for pull uploads, because it sends the file from your local filesystem. Pull uploads use a single, simple API call:

`$lib->request('/me/videos', array('type' => 'pull', 'link' => $url), 'POST');`

**Comment by ingageco** [comment]
@Dashron Is there a "pull" option for image uploads that works the same as your video pull option?

**Comment by Dashron** [comment]
Sorry for the delay! This is not currently supported, but is something we are interested in adding. An email will go out when it's available!

**Comment by ingageco** [comment]
Thanks @Dashron
