### ISSUE TITLE
DELETE ticket needs video_id and signature

### ISSUE THREAD

**Issue by pinoniq** [vimeo/vimeo.php#85]
It seems DELETE needs a video_id and a signature.

But these are not being set when calling the endpoint with DELETE.

The documentation is however now at all clear what these are, neither video_id or signature are clear so I can't get it to work...

**Comment by Dashron** [comment]
Are you manually making the delete call, or using the `upload` method: https://github.com/vimeo/vimeo.php#upload-videos-from-the-server?

**Comment by pinoniq** [comment]
Im manually calling the DELETE, the upload is handled on JS side using the JS File api.

I just tested using the vimeo.php to do the entire upload; and I get the same error however. Vimeo api returns that the video file could not be found (since video_file_id is not returned in the complete_uri). Hell, complete_uri itself simply is no longer returned by the api...

**Comment by Dashron** [comment]
The upload ticket provides the URL you should DELETE (under the key `complete_uri`). You should not be building this link yourself, as there is additional information signed into that uri that clients will not have access to.

**Comment by pinoniq** [comment]
Figured that one out. Documentation is however not that clear about that

**Comment by Dashron** [comment]
Cool, glad it's fixed.

The documentation actually recommends you use the built in methods entirely, and on site documentation never mentions what the contents of the complete_uri are, just that you should use that exact url. 

What documentation were you originally looking at?

**Comment by pinoniq** [comment]
This one: https://developer.vimeo.com/api/upload/videos#resumable-http-put-uploads

**Comment by Dashron** [comment]
Thanks! I'll look into it.
