### ISSUE TITLE
Additional  method

### ISSUE THREAD

**Issue by thorstenHe** [vimeo/vimeo.php#87]
Update metadata method would be nice

**Comment by Dashron** [comment]
This library is intended to be the minimum library possible. In the future we might build a second library that offers direct method calls to the various available api calls, but for now we only offer methods when a workflow can be entirely automated by the library (such as one of our many upload methods)

For now, you can edit metadata using the `request` method as documented here: https://github.com/vimeo/vimeo.php#make-requests
