### ISSUE TITLE
Channel, album and group name not present in GET result

### ISSUE THREAD

**Issue by thorstenHe** [vimeo/vimeo.php#88]
```
"albums" => array:3 [▼
            "uri" => "/users/12345/albums"
            "options" => array:1 []
            ]
            "total" => 2
          ]
...
"channels" => array:3 [▼
            "uri" => "/users/12345/channels"
            "options" => array:1 []
            "total" => 0
          ]
...
"groups" => array:3 [▼
            "uri" => "/users/12345/groups"
            "options" => array:1 []
            "total" => 1
          ]

```

The 2, 0, 1 are not really helping. The request result does not how any of the group names that I have assigned on the vimeo page. One video is even assigned to two albums (2). The channel is not even shown.

**Comment by Dashron** [comment]
Can you send the actual album, channel or group id? If you are not comfortable sharing it here, contact us at vimeo.com/help/contact and reference this issue.

**Comment by thorstenHe** [comment]
https://vimeo.com/forums/api/topic:278555
