### ISSUE TITLE
this files is not working 

### ISSUE THREAD

**Issue by sdhiman493** [vimeo/vimeo.php#89]
hello sir 
i have download this file and follow all the steps of this url http://zinclabs.com/VimeoAPIforPHP.html
but i have get a error and this folder in index.php file are missing.

**Comment by Dashron** [comment]
The link you provided is for an old version of the PHP library. We do not yet have a getting started guide like the document you linked, but we're working on it!

**Comment by Dashron** [comment]
In the meanwhile, our new index.php is inside of the examples directory (https://github.com/vimeo/vimeo.php/blob/master/example/index.php). 

Make sure to add a config.json file inside of the example directory, that is similar to config.example.json (the only difference being you should add your tokens to the file!). Once the config is ready, type `php index.php` to see more information about your user account!

**Comment by sdhiman493** [comment]
please provide us the link for the new current php library.

Thanks & Best Regards

      Sunny Dhiman

           Mobile:9813203570

**Comment by sdhiman493** [comment]
we generate a access token for our application.this give us censored token
like
XXXXXXXXXXXXXXXXXXXXXXXXXXXXd521.how to use this access token in config.json

the following is the code of my config.json file

{
    "client_id" : "62eee18d2b897a5d4feafea2377a64478ce79952",
    "client_secret" :
"mtPdElzbwtd8ZywG8dAKi+2HOszLxY8IUtntUpFMb5rh+R4mMVI+Fh5DPMvF9luADmhTgirdJ6negOgxyfIk09a56/gnWazC33IeE3xrd81ndCQ5od1fuoB3aSayLF91",
    "access_token" : "XXXXXXXXXXXXXXXXXXXXXXXXXXXXd521"
}


this gives me access token failed error.

So, reply asap. Thanks



Thanks & Best Regards

      Sunny Dhiman

           Mobile:9813203570

**Comment by Dashron** [comment]
When you generate an access token, it will show you the full token once. If you refresh the page, it will become censored.

Make sure to record the token before it becomes censored, otherwise you will need to generate a new one.
