### ISSUE TITLE
Using the library to update meta data

### ISSUE THREAD

**Issue by ghost** [vimeo/vimeo.php#9]
Hi - 

You mention in the readme that you are able to set meta data using the library but I've so far been unsuccessful and I was hoping for some guidance. At the moment I'm uploading the video successfully, I then call this function to try and setTitle:

$lib->request('/api/rest/v2', array('method'=>'vimeo.videos.setTitle', 'title' => $post_title, 'video_id' => $video_id ) );

But get a 'Page was not found' in return.

Any help? 

Thanks in advance,
Helen

**Comment by mahaveer003** [comment]
Hi,
I want help. How to delete Video with new api
I tried this one 
$lib->request('/videos/' . $video_id, array(), 'DELETE');

**Comment by Dashron** [comment]
@mahaveer003 , this probably should be in a new ticket, but that code should work. What response did you get from the server?
