### ISSUE TITLE
Hide owner and potrait

### ISSUE THREAD

**Issue by goodygem** [vimeo/vimeo.php#91]
Hi 

I have a Vimeo Pro account.
I have created a page where I can upload videos to vimeo using the API. Everything works fine so far except for the videos information. I am trying to hide owner and portrait information on the uploaded video by doing the following:

$metainfo = array(
      'embed' => 'title' = array(
                             'owner' => 'hide',
                             'portrait' => 'hide'
                         )
);

This does not seem to make any difference. The information is still showing on the videos.

Can you help?

**Comment by agilefox** [comment]
@goodygem , This sounds more like a bug in the API then in the library. I'll look into it. Thanks!

**Comment by agilefox** [comment]
This does seem to be an issue with the API. I'll update this ticket when a fix is pushed.

**Comment by goodygem** [comment]
@agilefox Thanks for the info. I will keep checking. 
Cheers

**Comment by agilefox** [comment]
@goodygem The fix has been released. Thank you again for pointing it out!
