### ISSUE TITLE
How to get get video id and url from metadata received

### ISSUE THREAD

**Issue by saniaaa** [vimeo/vimeo.php#93]
I want to get url of all videos for an album on Vimeo. For this first of all I am using PHP libraries to get a list of albums on Vimeo by following code.
$api_endpoint = 'http://vimeo.com/api/v2/' . $vimeo_user_name;

$albums = simplexml_load_string(curl_get($api_endpoint . '/albums.xml'));

```
<? foreach($albums->album as $album) { 
echo $album->id 

//After getting album id i have to get url of all videos for this album id in next foreach loop

$AlbumVideos = curl_get($api_endpoint . '/' . $album->id . '/videos');
    foreach($AlbumVideos->video as $video) 
    {echo video->url;}
} ?>
```

I got error here $AlbumVideos->video as $video as i am not able to guess the data structure for $AlbumVideos. Need help please.

Thanks in advance

**Comment by erunion** [comment]
I'm going to close this ticket out.

You aren't using the vimeo.php library here in your code example, and also your API request is for our Advanced API, which has been deprecated. 

Check out our API v3 documentation for this specific feature you're trying to execute for more information: https://developer.vimeo.com/api/endpoints/albums#/{album_id}/videos
