### ISSUE TITLE
Upload directly to an album?

### ISSUE THREAD

**Issue by MACscr** [vimeo/vimeo.php#95]
Is there a way to upload directly to an album or do I just have to upload it first, then assign it to an album?

Something like so doesnt work unfortunately: $lib->request('/me/album/3871852/videos', array('type' => 'pull', 'link' => $url), 'POST');

**Comment by Dashron** [comment]
You have to upload first, and then assign it to the album. We've been thinking about offering some more immediate actions in the upload flow (such as add to album), but they are not yet available. Sorry!

**Comment by MACscr** [comment]
Maybe I should open a new ticket for this, but isn this the proper method for moving it to a new album? Doesnt appear to be the case:

`$lib->request('/me/videos/albums/3871852/videos/'.$video_id,'', 'PUT');`

**Comment by Dashron** [comment]
the videos part in the url is incorrect.

This is the correct url:

`'/me/albums/3871852/videos/' . $video_id`

Docs can be found here: https://developer.vimeo.com/api/endpoints/me#PUT/me/albums/{album_id}/videos/{video_id}
