### ISSUE TITLE
How do I set the published date?

### ISSUE THREAD

**Issue by MACscr** [vimeo/vimeo.php#96]
I have tons of old videos that I am going to import into my Vimeo Pro account. I am not seeing any api options for setting the publication date. Am I missing something?

**Comment by Dashron** [comment]
Vimeo does not currently support "publish in the future" functionality on site, or via the API. The easiest option would be to upload them all as private, and mark them public at some point in the future.

**Comment by MACscr** [comment]
I wanted to actually set the dates in the past since they are older videos.

- Mark

**Comment by Dashron** [comment]
Ah, unfortunately that is also not possible. We only store an "uploaded on" date, not a published on date.

Vimeo On Demand has some additional options here (such as release year), but that's for a very  specific use-case

**Comment by bsync** [comment]
I think I am discovering that most detailed information like this must be maintained outside of Vimeo. Vimeo can barely keep the videos organized in showcases/albums/folders or whatever they are calling it lately.  I would recommend using something more capable like maybe a redis instance to store detailed info about the vimeo videos.

**Comment by hjhimanshu01** [comment]
@Dashron , does it now have a "publish in future" feature? looking for the same

**Comment by CyberCyclone** [comment]
This issue should not have been closed as it's a necessary feature. At this point it makes moving content to Vimeo very difficult as we now can't use the "published" / "uploaded" date to determine when the video was released.
