### ISSUE TITLE
Upload on Click

### ISSUE THREAD

**Issue by fre2mansur** [vimeo/vimeo.php#97]
Upload on on click event. ets very hard to use drag only

**Comment by Dashron** [comment]
Which upload are you talking about? The form that we return in the POST upload workflow?

**Comment by fre2mansur** [comment]
Hi, sorry i was post a issue in wrong place.. actually im trying for here
https://github.com/websemantics/vimeo-upload

**Comment by Dashron** [comment]
No worries!
