### ISSUE TITLE
Problem with upload

### ISSUE THREAD

**Issue by paolocomis** [vimeo/vimeo.php#98]
Hello,
I'm a registered user with the PRO account. I use this library for some time with a bash script that I created that recalls the "upload.php" script to upload video, if present in a folder.
Usually there are many videos in the folder and load cycle until you empty the folder.
Recently, the library to be output in this error:

(Standard_in) 1: syntax error
(Standard_in) 1: syntax error
(Standard_in) 1: syntax error
(Standard_in) 1: syntax error
(Standard_in) 1: syntax error
(Standard_in) 1: syntax error
(Standard_in) 1: syntax error
PHP Fatal error: Uncaught exception 'Vimeo \ Exceptions \ VimeoRequestException' with message 'Unable to complete request. [Connect () timed out!] 'In /root/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php: 154
Stack trace:
#0 /root/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(403): Vimeo \ Vimeo-> _REQUEST ( 'https: // 1511923 ...', Array)
#1 /root/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php(320): Vimeo \ Vimeo-> perform_upload ( '/ root / GOLCAM / Te ...', Array)
#2 /root/vimeophp/script/upload.php(34): Vimeo \ Vimeo-> upload ( '/ root / GOLCAM / Te ...')
#3 {main}

  thrown in /root/vendor/vimeo/vimeo-api/src/Vimeo/Vimeo.php on line 154
After the second or third attempt is the video upload properly.

I use this library for over a year, but these errors began in early April to date.

Want to help me solve this problem? Thanks in advance

**Comment by agilefox** [comment]
This doesn't sound like a Library issue, but more of a Vimeo upload server issue. Submit a ticket [here](https://vimeo.com/help/contact#tech-api) with more details (ticket id, video size, anything else you can think of) and they will get the proper people on it.
