### ISSUE TITLE
Uploading videos from a public url (Pull uploads) doesn't work?

### ISSUE THREAD

**Issue by khurshid-alam** [vimeo/vimeo.php#99]
I just can't make pull uploads to work. I have tried uploading with several direct urls (from dropbox, gdrive..etc) but it didn't work. 

**_Default privacy settings_**: `Only people I choose`
**_Permissions (for my app):_** `public private create edit delete interact upload` 

**CODE:**

``` php
$token = file_get_contents("access_token");
$client_id = "...........................................075gdft";
$client_secret = "OPHmyAXXXXXXXXXXXXXXXXXXXXX";
$vimeo = new \Vimeo\Vimeo("$client_id", "$client_secret");
$vimeo->setToken("$token");
$response = $vimeo->request('/me/videos', array('type' => 'pull', 'link' => 'https://117xxxxxxxxxxx.googledrive.com/host/JUIXXXXXXXXXXXX/recording22.mkv'), 'POST');

print_r($response);
```

I got following response:

``` Array
(
    [body] => Array
        (
            [uri] => /users/MYUSERNAME/tickets/1bebxxxxxxxxxxxxxxxx
            [ticket_id] => 1bebxxxxxxxxxxxxxxxx
            .....
            ......

            [upload_link] => http://1511928447.cloud.vimeo.com/upload?ticket_id=1bebxxxxxxxxxxxxxxxx&video_file_id=xxxxxxxx&signature=........
            [upload_link_secure] => https://1511928447.cloud.vimeo.com/upload?ticket_id=1bebxxxxxxxxxxxxxxxx&video_file_id=xxxxx&signature=..............
            [form] => <form method="POST" action="http://1511928447.cloud.vimeo.com/upload?ticket_id=1bebxxxxxxxxxxxxxxxx&video_file_id=xxxxxxxx&signature=................." enctype="multipart/form-data">
        )
)
```

**But the video never appears to my account**. Do I need to do anything else with `upload_link` or `upload_secure_link`??

**Comment by khurshid-alam** [comment]
Looks like I am not only one who is experiencing the same issue. https://vimeo.com/forums/topic:267870

**Comment by Dashron** [comment]
We're investigating now, The response you receive is the response for POST uploads, so there may be an issue with the parameters. We'll reach back out shortly when we have more details.

**Comment by Dashron** [comment]
We have been unable to reproduce this issue. Do you still see it? If so, reach out to us at vimeo.com/help/contact and we can dig in further.

**Comment by costajohnt** [comment]
Make sure your Vimeo account is using the correct API.  I had a similar issue and it was because my accounts API was defaulted to v3.0, and automatic "pull" uploads are not available in that version.  I needed Vimeo support to upgrade my account to v3.2 to get them to work.

**Comment by khurshid-alam** [comment]
@costajohnt How can you check your account version? Thank.

**Comment by Dashron** [comment]
@costajohnt The current version of this API library always uses version 3.2 of the API (https://github.com/vimeo/vimeo.php/blob/master/src/Vimeo/Vimeo.php#L33).

Your account level API version only applies if you do not provide any version information in your API request. 

If you are using an old version of the library, I highly recommend you update to resolve a handful of bugs we encountered over the last year or two.

**Comment by Dashron** [comment]
@khurshid-alam You  can check your account API version on your app page (e.g. https://developer.vimeo.com/apps/#####)

**Comment by khurshid-alam** [comment]
@Dashron 

My version is at 3.2. But I can always use `Accept: application/vnd.vimeo.*+json;version=3.2` in request header. Can't I?

As for this library I am using 1.2.3. I will try with the latest version and report back here.

**Comment by Dashron** [comment]
Correct, applying the accept header should lock you to 3.2 and you shouldn't see the issue mentioned above .

**Comment by herbdierks** [comment]
I ran into a similar issue, but I was using version 3.4.  It turned out that I needed to explicitly set a header for Content-Type to "application/json" on my request.  I hope this helps someone else in the future!

**Comment by dclaydev** [comment]
While I'm not using the PHP library, I'm using the NodeJS / Javascript library.  When I attempt to do a pull upload from a secure public URL (i.e. https://) i do get a response from Vimeo and the asset is created in my account, but the video never finishes its transcode process and is left with the vertical color bars as the thumbnail.  What's the deal here?  Any ideas?

**Comment by erunion** [comment]
@dclaydev Please contact our support team, they should be able to investigate what happened.

https://vimeo.com/help/contact

**Comment by rochella0527** [comment]
how to set the Content-Type to "application/json" on the request.  ? herbdierks
